### PR TITLE
Standardizing on 12pt point font

### PR DESCRIPTION
**Pull request by microsoftsam**
Best for our target age group.
Fixing RTL trash icon

Mostly relevant for the docs.

### CODE REVIEW

**Comment by pelikhan** [comment]
Screenshot?

**Comment by microsoftsam** [comment]
screen shot 2017-08-12 at 7 51 39 am
screen shot 2017-08-12 at 7 50 22 am

**Comment by pelikhan** [comment]
We need to give a heads up to the foundation about this.

**Comment by microsoftsam** [comment]
@jaustin FYI

**Comment by zdshelby** [comment]
Guys - Jonny is out this week, OK to wait until he is back? Looks like you went from a 16pt to a 12pt font. Can't tell the difference from the screen shots - before and after would be helpful.

**Comment by microsoftsam** [comment]
No change in the font size of /docs (went from 16px to 12 pt -- which is equivalent), but the main change was in the sidedocs (13px to 16px / 12pt). see above screenshot. Font is much easier to read. For comparison, this is what it looked like before: 
 
screen shot 2017-08-15 at 1 45 42 am

**Comment by microsoftsam** [comment]
Migrated change to the accessibility branch, once @jaustin approves this fix, we can close this PR.

**Comment by pelikhan** [comment]
This one is folded in Accessibliity right? @microsoftsam can you close it?

**Comment by microsoftsam** [comment]
It is. Closing.

**Comment by jaustin** [comment]
@microsoftsam I have done a side-by-side on the acc branch and live, and can't see a difference at all:

image

Just so I know I've checked the right thing, is that what I should be comparing?

**Pull request closed without merging**
