### PR TITLE
Cherry pick #6679 to chibitronics beta

### PR DESCRIPTION
**Pull request by riknoll**

### CODE REVIEW

**Comment by abchatra** [comment]
Conflicts?

**Comment by riknoll** [comment]
Whoops, wrong base branch

**Comment by riknoll** [comment]
Fixed now

**Comment by pelikhan** [comment]
Make sure that this bump does not upload anything to crowdin.

**Comment by riknoll** [comment]
@pelikhan done! Along with all the other stable branches

**Comment by pelikhan** [comment]
deployed?

**Comment by riknoll** [comment]
Nope, can you approve so that I can merge?

**Pull request merged**
