### PR TITLE
Remove playground tasks from gulpfile

### PR DESCRIPTION
**Pull request by shakao**

### CODE REVIEW

**Comment by livcheerful** [comment]
Why don't we want playground in the gulpfile now? 😅

**Comment by jwunderl** [comment]
These files were copying over the builtin livs for e.g. array methods and string methods - now that its using targets directly we dont need those anymore. 

Can we delete the duplicates of the builtin libs this copies over now too?

**Comment by shakao** [comment]
no, i believe the pxt-common files are still used by the test host/runners

**Comment by jwunderl** [comment]
Ahh oops, I meant the copies in the docs not the sources, but I just noticed that these were already deleted with your previous change. So good to go!

**Pull request merged**
