### PR TITLE
update language about static python experimental

### PR DESCRIPTION
**Pull request by mavaddat**
Re enabling experiments, I borrowed language from @pelikhan on https://github.com/microsoft/pxt/issues/5390

### CODE REVIEW

**Review by mavaddat — COMMENTED** [review]
I added the word "yet" instead of "for you" to avoid redundancy and build positive anticipation.

**Review by dmonroym — APPROVED** [review]

**Comment by jwunderl** [comment]
Hm, were there any editors with python enabled only as an experiment? I thought it was fully enabled in any of the editors where it is possible to enable it at the moment (micro:bit, minecraft, arcade, maker) -- change looks good if it is hidden behind an experiment anywhere though!

**Review by jwunderl — APPROVED** [review]

**Comment by mavaddat** [comment]
> Hm, were there any editors with python enabled only as an experiment? 

I was wondering that too: thinking maybe the hint author was saying that static Python was *no longer* experimental. If that's the case, I can modify the first sentence so it says something like, "Static Python is now available for all MakeCode releases!" or, "Static Python has graduated from experimental release, so all MakeCode editors can now use it."

N.B., I try to avoid language like *no longer experimental*, since it can appear to the eye (skim reading) as suggesting unavailability.

**Comment by jwunderl** [comment]
Yes, that's a good point -- I'm not sure I would say 'All MakeCode releases' as we have several editors that are supported but have not been updated since the implementation of python support (e.g. adafruit). Tagging in @ganicke here as I'm sure he'll have a good idea on how to phrase it :)

**Comment by ganicke** [comment]
With Python as a standard language option for micro:bit, Arcade, and Minecraft, I think note should say more that "Support for Static Python might still be experimental for some MakeCode editors. If `Python` isn't shown as a language choice in the editor you're using, you can enable it by..."

**Comment by jwunderl** [comment]
Thank you for your contribution! :)

**Comment by mavaddat** [comment]
Ah shoot &mdash; the `&mdash;` html entity does not render on [the webpage](https://makecode.com/language) as an em-dash. Can someone just change the html entity to [the equivalent unicode character](https://www.compart.com/en/unicode/U+2014) “—”?

**Comment by jwunderl** [comment]
Good catch, put up change replacing it~

**Pull request merged**
