### PR TITLE
Add AudioContextManager.playInstructionsAsync

### PR DESCRIPTION
**Pull request by mmoskal**
This allows for multi-channel sounds in the sim

### CODE REVIEW

**Comment by riknoll** [comment]
I think this needs to be cancellable, or maybe you could just check the runtime id in the loop to see if it has changed?

**Comment by mmoskal** [comment]
Well, it's only used to play a single note (the different entries are for attack, decay, etc). I guess there's risk someone will play a really long note.

**Comment by riknoll** [comment]
We've gotten bugs before of people doing that with the old audio context stuff. Would be good to add a `killAllAudio()` function or something that we can call when the simulator is paused or stopped.

**Comment by mmoskal** [comment]
Yeah, can do. IE is not supported (sound playing should be equivalent to pause)

**Comment by pelikhan** [comment]
As long as it does not crash

**Pull request merged**
