### PR TITLE
New carousel

### PR DESCRIPTION
**Pull request by microsoftsam**
Remove react-slick
Add new carousel 
Many UI fixes to the home screen

Tested on: 
- [x] IE: Works fine
- [x] Edge: Works fine
- [x] Chrome: Works fine

Issues:
- [ ] animation need easing in-out
- [ ] tried to drag the carousel to the right and got stuck
image
- [ ] Disabled class on the nav buttons: need indication that one cannot scroll anymore. currently, nothing seems to happen

### CODE REVIEW

**Comment by pelikhan** [comment]
- animation need easing in-out
- tried to drag the carousel to the right and got stuck
image

**Comment by microsoftsam** [comment]
IE issue: https://github.com/Microsoft/pxt/issues/2985

**Comment by microsoftsam** [comment]
@riknoll I don't know what I was doing, but I got this error: 
```
Uncaught (in promise) TypeError: Cannot read property 'getBoundingClientRect' of null
    at Carousel.updateDimensions (main.js:2937)
    at Carousel.componentDidUpdate (main.js:2930)
    at CallbackQueue.notifyAll (main.js:45305)
    at ReactReconcileTransaction.close (main.js:57424)
    at ReactReconcileTransaction.closeAll (main.js:60264)
    at ReactReconcileTransaction.perform (main.js:60211)
    at ReactUpdatesFlushTransaction.perform (main.js:60198)
    at ReactUpdatesFlushTransaction.perform (main.js:58257)
    at Object.flushBatchedUpdates (main.js:58318)
    at Object.wrapper [as flushBatchedUpdates] (main.js:56904)
    at ReactDefaultBatchingStrategyTransaction.closeAll (main.js:60264)
    at ReactDefaultBatchingStrategyTransaction.perform (main.js:60211)
    at Object.batchedUpdates (main.js:52984)
    at Object.enqueueUpdate (main.js:58347)
    at enqueueUpdate (main.js:57935)
    at Object.enqueueForceUpdate (main.js:58054)
main.js:2937 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at Carousel.updateDimensions (main.js:2937)
    at main.js:2926
main.js:2937 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at Carousel.updateDimensions (main.js:2937)
    at main.js:2926
main.js:2937 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at Carousel.updateDimensions (main.js:2937)
    at main.js:2926
```
probably worth a null check somewhere

**Comment by pelikhan** [comment]
LGTM. There's a couple improvement that we could make on the carousel but it's a great start already!

**Comment by microsoftsam** [comment]
Lets fix those errors before merging

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
It might take a while to get a perfect carousel. let's get it in so that we can start testing.

**Pull request merged**
