### PR TITLE
Default while loop to false (#1849)

### PR DESCRIPTION
**Pull request by pclemon**
Fixes: https://github.com/microsoft/pxt-arcade/issues/1849
Note: The second commit was to fix indentation that was missed with the first commit.

### CODE REVIEW

**Comment by jwunderl** [comment]
This was meant to modify https://github.com/microsoft/pxt/blob/master/webapp/src/blocksSnippets.ts, correct? Right now it's adding a new file at the base of the repo (that is, it's adding the file `pxt/blockSnippets.ts`)

**Comment by pclemon** [comment]
@jwunderl Yes, I am sorry. This is my first pull request. How should I fix it?

**Comment by jwunderl** [comment]
Oh no worries at all, github can be confusing to get used to! How did you make this pull request? (there are a few different ways to create one - from the command line, from an app, from github itself, etc)

**Comment by pclemon** [comment]
I made it via github's website.

**Comment by jwunderl** [comment]
Sounds good! If you want to do it that way, you can go to https://github.com/pclemon/pxt/blob/master/webapp/src/blocksSnippets.ts, click 'edit this file' in the top corner, and paste in the changes you made to this file.

image

Then, you can delete the duplicate file by going to https://github.com/pclemon/pxt/blob/master/blocksSnippets.ts and pressing the delete button that is next to the edit button:

image

**Comment by pclemon** [comment]
Okay. I think I fixed it!

**Comment by jwunderl** [comment]
@pclemon Thanks a bunch for fixing this! It should be included in https://arcade.makecode.com/beta soon ~

**Comment by abchatra** [comment]
Awesome  @pclemon

**Comment by jwunderl** [comment]
@pclemon Your fix is now included in https://arcade.makecode.com/beta, thanks again!

image

**Pull request merged**
