### PR TITLE
remove codecard from blocks editor

### PR DESCRIPTION
**Pull request by pelikhan**
This PR removes the automatic codecard when clicking on a block.
- Codecard gets in the way
- Introduces a small delay to render the card
- Description of the blocks is available in the tooltip
- Full help still available on the context menu

### CODE REVIEW

**Comment by abchatra** [comment]
Is it better to have an option to close the codecard instead of removing it?

**Comment by pelikhan** [comment]
Currently it opens up on each selected block, so the user would end up closing the codecard constantly.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/issues/965

**Comment by pelikhan** [comment]
Replaced by https://github.com/Microsoft/pxt/pull/1033

**Pull request closed without merging**
