### PR TITLE
display "help" next to "?" in desktopwide

### PR DESCRIPTION
**Pull request by pelikhan**
When space is available, "Help" is display on the nav menu next to the ?.

### CODE REVIEW

**Comment by abchatra** [comment]
:+1

**Comment by pelikhan** [comment]
The hamburger menu should also have "More" when "help" is displayed. Otherwise it gets sandwiched between the 2 icons.

**Comment by microsoftsam** [comment]
"More" for the hamburger menu or "Tools"??

**Comment by pelikhan** [comment]
"More" for the hamburger menu. Do we have a "Tools" menu? Hamburger is more like the traditional "File" menu.

**Comment by microsoftsam** [comment]
Add package, Project Settings and Reset are "Tools" to me. 
About, could also be considered tools.

Since we've moved "New Project" out, I think "Tools" is a better fit for this menu.

**Comment by pelikhan** [comment]
Outdated.

**Pull request closed without merging**
