### PR TITLE
Only show save and exit if the project has not been renamed

### PR DESCRIPTION
**Pull request by riknoll**

### CODE REVIEW

**Comment by riknoll** [comment]
What do you want the text to say? Should the affirmative button still say save?

**Comment by abchatra** [comment]
Save is fine as it is shown only once until you rename.

**Comment by abchatra** [comment]
Rename means you have already named it once.

**Comment by riknoll** [comment]
So what should the text say?

**Comment by pelikhan** [comment]
We already have a similar purpose dialog when clicking on the save button: 
image

**Comment by abchatra** [comment]
Sorry Peli it is not rename. Rename means they have named it once. @Jaqster tie breaker please.

**Comment by abchatra** [comment]
Maybe "Name your project"

**Comment by pelikhan** [comment]
We already have a dialog that is used to rename a project before saving, we should reuse it or fix it.

**Comment by abchatra** [comment]
Yes agree "Name your project and Exit"

**Comment by Jaqster** [comment]
Just to be clear, the behavior is:
1.) User is working on a named project already, clicks on the Home button - no dialog, gets taken to Home (his named project is at the front of My Stuff)
2.) User is working on an Untitled project, clicks on the Home button - pop this dialog giving them the opportunity to Name their project before going back to Home.

In the 2nd case, the dialog should say Project Name: <textbox here with default Untitled> with an "Exit" and "Cancel" button.  If the user doesn't want to name their project, they don't have to, they can simply click Exit.

Make sense?

**Comment by pelikhan** [comment]
Exit Minecraft? I find this dialog confusing and I don't understand what the point is.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jaqster** [comment]
No, exit your project.  And as part of exiting your program, we want to give them the opportunity to name their project if they haven't already.

**Comment by Jaqster** [comment]
Can we rename this dialog box?
Would like the title to be "Exit Project", and the green button to be "Exit" (instead of Save)
exit dialog

**Pull request merged**
