### PR TITLE
Clear indexed db on reset

### PR DESCRIPTION
**Pull request by livcheerful**
Lemme know if we don't want this - I'm adding this for https://github.com/microsoft/pxt-minecraft/issues/1936 , since Sheila expected the Reset button to help her recover, but it didn't

### CODE REVIEW

**Comment by riknoll** [comment]
Seems like the right behavior to me. @pelikhan @abchatra FYI

**Review by jwunderl — APPROVED** [review]

**Comment by pelikhan** [comment]
Not waiting on the promise?

________________________________

**Comment by abchatra** [comment]
Cleanup is the right thing to do. But should await on the async call?

**Comment by eanders-MS** [comment]
You can explicitly not await by calling `.done()`. It's essentially an empty `.then` handler.

**Pull request merged**
