### PR TITLE
Add editor controller command for importing custom.ts file

### PR DESCRIPTION
**Pull request by shakao**
New "importcustomblocks" editor controller command, to be used by updated playground.

### CODE REVIEW

**Comment by riknoll** [comment]
Should we just use the existing importproject? Otherwise, code looks good

**Comment by shakao** [comment]
i can modify importproject! but i don't think there's a way to do this without changes to pxt since i have to pull the default project template from pxt.appTarget, right?

**Comment by pelikhan** [comment]
once the editor is opened, you should receive the project when it tries to save it. You can use that to add/modify custom.ts and reinject it back.

**Comment by riknoll** [comment]
@shakao check out the workspacesync event

**Pull request closed without merging**
