### PR TITLE
Fix component governance alerts

### PR DESCRIPTION
**Pull request by abchatra**
Fixes
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/119762/alert/6720712?typeId=795877
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/119762/alert/6651919?typeId=795877

### CODE REVIEW

**Comment by abchatra** [comment]
ran `npm audix fix` in skillmap

**Comment by abchatra** [comment]
Arcade list: https://devdiv.visualstudio.com/DevDiv/_componentGovernance/121300
Microbit list: https://devdiv.visualstudio.com/DevDiv/_componentGovernance/119762

**Review by jwunderl — APPROVED** [review]
This looks fine (doesn't touch react-scripts dep which had some potentially breaking changes in v4->5), but should wait for Shannon's review as well to make sure~

**Comment by abchatra** [comment]
@shakao ?

**Review by shakao — APPROVED** [review]

**Pull request merged**
