### PR TITLE
Command parser

### PR DESCRIPTION
**Pull request by riknoll**
Adds a proper command line parser to the cli. Nothing fancy, but better than what we had.

```
$ pxt help

Usage: pxt <command>

Commands:
    help ....... display this message or info about a command
    deploy ..... build and deploy current package
    run ........ build and run current package in the simulator
    update ..... update pxt-core reference and install updated version
    install .... install new packages, or all package
    add ........ add a feature (.asm, C++ etc) to package
    login ...... stores the PXT or GitHub access token
    logout ..... clears access tokens
    bump ....... bump target or package version
    build ...... build current package
    extract .... extract sources from .hex file, folder of .hex files, stdin (-), or URL
    snippets ... verifies that all documentation snippets compile to blocks
    serve ...... start web server for your local target
    gist ....... publish current package to a gist
    init ....... start new package (library) in current directory

For more information on a command, try 'pxt help <command>'
```

You can also get help on individual commands:

```
$ pxt help serve

Usage:
    pxt serve [--browser chrome|ie|firefox|safari] [--noBrowser] [--sourceMaps] [--yt] [--pkg] [--cloud] [--just] [--electron]

start web server for your local target

Flags:
    --browser <chrome|ie|firefox|safari> ... set the browser to launch on web server start
    --noBrowser --no-browser ............... start the server without launching a browser
    --sourceMaps --include-source-maps ..... include souorce maps when building ts files
    --yt ................................... use local yotta build
    --pkg .................................. serve packaged
    --cloud ................................ forces build to happen in the cloud
    --just ................................. just serve without building
    --electron ............................. used to indicate that the server is being started in
                                             the context of an electron app
```

Please review all the commands/flags and make sure they are present and that they have the correct help text. The command parser will reject flags if an unrecognized flag is passed, so its important to make sure I didn't miss anything.

### CODE REVIEW

**Comment by riknoll** [comment]
Further work to do:

1. Add tests! (need a way to run the tests...)
2. Support named arguments

**Comment by OwenBrotherwood** [comment]
Did the --port option break?

**Comment by pelikhan** [comment]
Parsing of that command, fix coming.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/commit/226295a1f6a5fb524cd688652df472c91160ffb1

**Pull request merged**
