### PR TITLE
Hide share embed

### PR DESCRIPTION
**Pull request by pelikhan**

### CODE REVIEW

**Comment by abchatra** [comment]
@pelikhan can you explain the intent of the change?

**Comment by pelikhan** [comment]
Adds a theme option to hide all advanced "embed" sharing options. Merged from v2.

**Comment by abchatra** [comment]
Why is this getting merged to v0. I don't understand

**Comment by pelikhan** [comment]
Keeping v0 in sync.

**Comment by abchatra** [comment]
Lets keep the churn low in v0 and only merge fixes we need? Sync is not a priority right?

**Pull request closed without merging**
