### PR TITLE
Update monaco 0.19 -> 0.23

### PR DESCRIPTION
**Pull request by darzu**
Prerequisite for: https://github.com/microsoft/pxt-microbit/issues/3940

## Steps for updating Monaco (in this PR and hopefully useful for the future):

0. bump monaco-editor version in package.json & npm install
1. Patch monaco.tsx and other places where API changes might have occured
1. Download latest codicon (https://github.com/microsoft/vscode-codicons/blob/main/dist/codicon.ttf) and replace version at (theme/external-font/codicon.ttf)
2. Verify all the paths match up (in this PR, `ui/codiconLabel/codicon/codicon.ttf` had to be changed to `ui/codicons/codicon/codicon.ttf` based on new monaco-editor paths)
0. run gulp (this runs the `copyMonaco` task), check in all the changes
0. update localtypings/monaco.d.ts from node_modules/monaco-editor/

## Test plan:

0. test specifically on iOS and android to ensure we don't regress
1. Check that all the icons are present
2. Test large JS and PY projects, try features like find and replace, text selection, go to line, command palette

Try it here: https://arcade.makecode.com/app/e1d966184d6fd748667a9a38283c3c02f00df890-68169a79a7

### CODE REVIEW

**Review by eanders-MS — APPROVED** [review]
> The steps I used:
> 
> 1. bump monaco-editor version in package.json
> 2. run gulp
> 3. commit changes

Test? Assuming it works, LGTM.

**Comment by abchatra** [comment]
You need to test iPad & andorid and ensure it is atleast as good as in the older version.

**Comment by abchatra** [comment]
Also I see they dropped support for old edge. Fine by me.

**Comment by darzu** [comment]
> You need to test iPad & andorid and ensure it is atleast as good as in the older version.

I don't have either device on me :(
I'll try with the MacOs device emulator

**Comment by darzu** [comment]
Tested a bit on the iPad emulator. Everything seems functional. Sprite editor works, search works, typing works, scrolling works.

**Comment by darzu** [comment]
Hey @riknoll,
Do you remember this history of why we diverged our codicon.ttf from Monaco's? Seems to have been done here:
https://github.com/microsoft/pxt/pull/6523/files#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7R356

I'm updating monaco and some of the icons were renamed.

**Comment by darzu** [comment]
> Hey @riknoll,
> Do you remember this history of why we diverged our codicon.ttf from Monaco's? Seems to have been done here:
> https://github.com/microsoft/pxt/pull/6523/files#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7R356
> 
> I'm updating monaco and some of the icons were renamed so now they're showing up as empty squares.

I think I figured it out:
https://github.com/microsoft/pxt/pull/6523/files#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7R392

Where did you get the valid codicon from? here? https://github.com/microsoft/vscode-codicons

**Comment by riknoll** [comment]
yeah, i think it was that repo

**Comment by darzu** [comment]
Waiting on help with Android testing....
 See test link in the summary.

**Comment by jwunderl** [comment]
It looks about the same to me, saw a different minor bug with soft keyboard but live site has a worse -- in the linked version it loses a character, in live monaco it repeats the characters if you press enter (large gif sorry D:)

android monaco

**Pull request merged**
