### PR TITLE
Tool for taking screenshots of blocks

### PR DESCRIPTION
**Pull request by riknoll**
This is a request we've gotten a few times, so here's a PR adapting the tutorial tool into a tool that lets you generate PNGs of blocks with no other blocks attached.

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]

**Review by kiki-lee — APPROVED** [review]
Looks amazing!

**Comment by dmonroym** [comment]
@Jaqster this could prove useful during the final pass of the TEALS curriculum

**Comment by riknoll** [comment]
@bmarslandCN @wedodge89

This is live now at https://makecode.com/screenshot-tool

**Comment by Jaqster** [comment]
Hooray!!!!  I love this!

**Comment by bmarslandCN** [comment]
This is amazing! Thank you @riknoll!!

I noticed we can only save files as SVGs - is there any way a PNG option could be added too? Thank you!!!

**Pull request merged**
