### PR TITLE
Display an error for floating point numbers if not supported

### LINKED ISSUE #2: prevent decimal numbers in blocks
When not supported (like microbit), floating point numbers should not be allowed.

image

### PR DESCRIPTION
**Pull request by riknoll**
Fixes #2 (mostly)

Makes using floating point numbers when targeting a board that does not support them an error. It looks like this:

decimal_errors

As part of this, I had to move the max-int check from the block compiler to the emitter, so typing in a huge number will give a similar error now. I also removed the max-float check because it didn't work (not sure if we want to add in a different working one?)

### CODE REVIEW

**Comment by riknoll** [comment]
Oh, I also just chose arbitrary numbers for the error codes. Is there a process for choosing those?

**Comment by pelikhan** [comment]
Yes there should be a "nextError" variable?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by riknoll** [comment]
Ahhh, it's in a comment. We should define these in a JSON file or something.

**Comment by riknoll** [comment]
Fixed

**Pull request merged**
