### PR TITLE
[stable6.4] cherry picks - Minecraft UI fixes (#7876)

### PR DESCRIPTION
**Pull request by livcheerful**
I got https://github.com/microsoft/pxt-minecraft/pull/2115 and https://github.com/microsoft/pxt/pull/7589

### CODE REVIEW

**Comment by livcheerful** [comment]
I tested this with the tutorial mentioned and it looks good. @abchatra i also cherry picked the pxt-minecraft change for testing, do you want me to put up a PR for that one too?

**Review by abchatra — APPROVED** [review]

**Comment by abchatra** [comment]
@shakao can you give a quick look for this hotfix as well?

**Comment by abchatra** [comment]
@livcheerful I will do the porting for the pxt-minecraft

**Comment by livcheerful** [comment]
okiee!

**Review by shakao — APPROVED** [review]

**Comment by shakao** [comment]
lgtm! long term we might want to move this "createModalClasses" thing into the base modal code so we don't have to remember to call it for every new modal we create

**Review by abchatra — APPROVED** [review]

**Pull request merged**
