### PR TITLE
Multi-chart support

### PR DESCRIPTION
**Pull request by pelikhan**
If a value is named ``aaa.bbb``, we collapse all values starting with ``aaa`` under the same graph.

multichart

- [ ] update docs (I could not find the docs on serial output)

### CODE REVIEW

**Comment by pelikhan** [comment]
We need to finish up the CSV output support. I think single chart output goes away but we still need to be able to dump the entire thing.

**Comment by pelikhan** [comment]
Needs a bit of skinning mostkly ready.

**Comment by pelikhan** [comment]
@microsoftsam

**Comment by pelikhan** [comment]
@caitlin-hennessy this PR is ready for mergin

**Comment by caitlin-hennessy** [comment]
@pelikhan This looks great! Can you please make a PR for v0 too?

**Pull request merged**
