### PR TITLE
Move target logos into app cache

### PR DESCRIPTION
**Pull request by samelhusseini**
Move target images out of target.json and over into the release manifest to reduce the size of target.json and allow us to make use of browser app cache for those images between releases. 

Works locally, need to test on the cloud.

### CODE REVIEW

**Comment by samelhusseini** [comment]
I tried it but no, it looks like the hero banner already had an issue with staticpkg. I was going to ping @guillaumejenkins tomorrow to see if he's aware of any of these issues. Basically we reference ./static/... but in static package that has to look like ./docs/static in order to get to the right location. Perhaps we patch the pxtarget that we generate.

**Comment by samelhusseini** [comment]
Fixed staticpkg. See: https://samelhusseini.github.io/test-pxt-sample
and https://samelhusseini.github.io/test-pxt-sample/release.manifest

**Comment by pelikhan** [comment]
Try uploadpkg as well and we should be good!

**Comment by samelhusseini** [comment]
FYI this does create more requests from the client (one for each image), but I think it's worth the compromise of caching between updates.

**Pull request merged**
