### PR TITLE
Chaning the name from kindscript to makecode

### PR DESCRIPTION
**Pull request by abchatra**
Documentation and other changes for prepping name change.

### CODE REVIEW

**Comment by pelikhan** [comment]
Can you ask crowdin for a redirect?

**Comment by abchatra** [comment]
Yes we should ask that too.

**Comment by abchatra** [comment]
@anzhou5 can you ask if they can do redirect if anyone tries to reach kindscript to new URL?

**Review by jwunderl — APPROVED** [review]
I believe there's an env variable in the backend (CROWDIN_PROJECT) set to kindscript as well that gets used when only when initializing a page for inContextTranslationMode (in serveFileAsync 
 in routing.ts)

**Comment by abchatra** [comment]
@jwunderl is that part of env.json?

**Comment by jwunderl** [comment]
Yes, it's in env.json

**Comment by abchatra** [comment]
Ideally it should be in pxt-deployment-config. It is not a secret.

**Pull request merged**
