### PR TITLE
Add ON / OFF description text onto the field toggle

### PR DESCRIPTION
**Pull request by microsoftsam**
onoff

### CODE REVIEW

**Comment by pelikhan** [comment]
Do we have a documented list of field editors?

**Comment by microsoftsam** [comment]
No but I was thinking we should add, plus add the list of parameters that they accept. Even though we have interfaces in the code, they're not exported and hard to find.

**Comment by pelikhan** [comment]
+ those amazing gifs :)

**Comment by microsoftsam** [comment]
Yeah I'll start preparing a docs page

**Pull request merged**
