### PR TITLE
Show offline message for Immersive Reader

### PR DESCRIPTION
**Pull request by livcheerful**
fixes https://github.com/microsoft/pxt-microbit/issues/4213

-> in the scenario where you don't already have the token and you're offline:
- this change properly handles the error and shows the offline message

-> in the scenario where you do have the token and you're offline
- I added a ping to check the connection before starting the launch to the immersive reader. the "Launch Immersive Reader" call doesn't fail quickly enough if there's no internet, so this shows the offline error instead of white-screening it for 15 seconds first

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]

**Comment by abchatra** [comment]
Can you elaborate what was the issue? I am not able to understand the fix.

**Comment by livcheerful** [comment]
to my knowledge, we don't have a super reliable way to tell if a user is offline. this change uses a different get request api that also interacts with the offline code to help trigger that, and also shortens the timeout of the immersive reader. default is 15 seconds. also adds a tick to see how long it typically takes to launch so we can adjust that

**Comment by abchatra** [comment]
5 sec may be too short for some geography like China. Is the bug because Cloud.isOnline() returned true but still there is no connectivity?

**Comment by abchatra** [comment]
Or another way to ask is, do we show the error message after 15 sec?

**Comment by abchatra** [comment]
Seems like share page does the right thing in offline app where it shows error message if there is no connectivity almost immediately. How much timeout does it have?

**Comment by livcheerful** [comment]
share page tries to make a post request. difference here is that instead of making a call to an API, we have to call to the Immersive Reader SDK. I can change it so it tries to ping one of our APIs first, and then launch the SDK instead

**Review by abchatra — APPROVED** [review]

**Pull request merged**
