### PR TITLE
Fixes table of content rendering

### PR DESCRIPTION
**Pull request by darzu**
This PR: https://github.com/microsoft/pxt/pull/6013
introduced a change that has to be rolled out to all editors simultaneously because of how the docs renderer <-> docfiles contract works.
This is too annoying to do, so this PR rolls back some of those changes and instead keeps the renderer as it was at the cost of some ugly code.

Eventually we should create a better contract between the renderer and the docfiles so changes like this aren't coupled.

### CODE REVIEW

**Comment by jwunderl** [comment]
https://github.com/microsoft/pxt/pull/6048?

**Comment by pelikhan** [comment]
> This is too annoying to do,

This is impossible to acheive as we would have to release all editors simultaneously.

**Comment by jwunderl** [comment]
I'd prefer #6048 as the explicit todos seem like it gives it a slightly higher chance of eventually cleaning up the tech debt

(and also just cleaned up a few more places in that branch / fixed a small bug as I was looking at what needed to be done for accessibility there)

**Comment by darzu** [comment]
Redundant with https://github.com/microsoft/pxt/pull/6048#pullrequestreview-300231380

**Pull request closed without merging**
