### PR TITLE
Add QR Code to Multiplayer Host Lobby

### PR DESCRIPTION
**Pull request by thsparks**
This adds a QR Code (containing the join deep link) to the host's lobby. I've brought in the [qrcode.react](https://www.npmjs.com/package/qrcode.react) package to generate the qr code itself.

image

image

Fixes https://github.com/microsoft/pxt-arcade/issues/5181

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]
LGTM, but i think you need to update packagelock before checking in?

**Comment by thsparks** [comment]
> LGTM, but i think you need to update packagelock before checking in?

Hmm you're probably right. Is that auto-generated, or do I need to update it manually?

**Comment by jwunderl** [comment]
I believe it should update if you run `npm i` in multiplayer folder

**Review by eanders-ms — APPROVED** [review]
:shipit:

**Pull request merged**
