### PR TITLE
Disabling file import dialog on all iOs

### PR DESCRIPTION
**Pull request by abchatra**
There is no support for files and they don't work today. We will reevaluate later if necessary

### CODE REVIEW

**Comment by abchatra** [comment]
Fixes https://github.com/Microsoft/pxt-minecraft/issues/672

**Comment by abchatra** [comment]
How is microbit using this?

**Comment by pelikhan** [comment]
You can import and export .hex files via iCloud. We had bugs in the past in that area and this is something that people have reported... so they use it.

**Comment by riknoll** [comment]
@pelikhan what would the authoring look like? Maybe we could take a list of platforms or something? Or maybe we should make this an editor extension and let the target run whatever code they want to detect if they can import files.

**Comment by pelikhan** [comment]
Any editor that can save and import file can use this feature. I don't understand why it has to be disabled on iOS.

**Pull request closed without merging**
