### PR TITLE
Nonlocalhost

### PR DESCRIPTION
**Pull request by dragonx**
Allow the serving hostname to be specified on command line.  This is
most useful for passing in ‘0.0.0.0’ or the external facing IP address to allow access from a network device (i.e. tablet or phone)

### CODE REVIEW

**Comment by abchatra** [comment]
@pelikhan Can you review this please?

**Comment by abchatra** [comment]
@dragonx  Can you please sign the CLA?

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by pelikhan** [comment]
@abchatra let's make a decision about this.

**Pull request merged**
