### PR TITLE
Pick random element from array block

### PR DESCRIPTION
**Pull request by jwunderl**
@darzu found the branch, it does work (as well as arrays in generally do at least), but not sure it's great too implement things as a methods just to get around generic types in blocks

### CODE REVIEW

**Comment by riknoll** [comment]
Eh, I think we should merge this.

It's super useful.

**Comment by jwunderl** [comment]
Okay, moved to "Read" group under arrays and cleaned up block to match others:

image

image

I guess maybe worth considering another 'get and remove random value' equivalent to match the other blocks as well

**Review by livcheerful — APPROVED** [review]
yusssss

**Comment by riknoll** [comment]
@abchatra obviously this deviates from the JS spec, but this is super useful as a block. Thoughts?

**Comment by abchatra** [comment]
Is there a pattern in the community games where they try to get the random value from the array? Where did the requirement for this block came from?

**Comment by livcheerful** [comment]
We do it a lot in stream at least! In today's stream we used it in three places: 

Spawning a random gemstone out of a mined rock:
image

Having the shark say random insults:
image

The shark picking a random thing to demand from you:
image

**Comment by pelikhan** [comment]
Good opportunity to teach functions.

________________________________

**Comment by livcheerful** [comment]
> Good opportunity to teach functions.
> […](#)
> ________________________________ From: Vivian Li <notifications@github.com> Sent: Friday, September 4, 2020 3:34:35 AM To: microsoft/pxt <pxt@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [microsoft/pxt] Pick random element from array block (#5972) We do it a lot in stream at least! In today's stream we used it in three places: Spawning a random gemstone out of a mined rock: [image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F18712271%2F92189641-0a6e9f80-ee14-11ea-817a-d431d87be38c.png&data=02%7C01%7Cjhalleux%40microsoft.com%7C0fb4b647ad6845978a6408d85072ae90%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637347800775135342&sdata=SAhrs5XWnjoWjjctiX8InTYL%2F7cRN9uKtag6kEI%2B330%3D&reserved=0> Having the shark say random insults: [image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F18712271%2F92189537-c7143100-ee13-11ea-9553-edeaa095773c.png&data=02%7C01%7Cjhalleux%40microsoft.com%7C0fb4b647ad6845978a6408d85072ae90%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637347800775135342&sdata=82OH3oifTEkehDGcyPDyuBPTH%2B1jy3Jwiqjl7%2BN7o9c%3D&reserved=0> The shark picking a random thing to demand from you: [image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F18712271%2F92189572-e448ff80-ee13-11ea-8b5e-7895e6af4cf2.png&data=02%7C01%7Cjhalleux%40microsoft.com%7C0fb4b647ad6845978a6408d85072ae90%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637347800775145334&sdata=x7ST2kTfJm3e0ocYJYXovfZt5DdeZHXsVtG%2BS4x1dxg%3D&reserved=0> — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fpxt%2Fpull%2F5972%23issuecomment-686848174&data=02%7C01%7Cjhalleux%40microsoft.com%7C0fb4b647ad6845978a6408d85072ae90%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637347800775145334&sdata=WdotVXb0VQalN284tpBK6JD81J8JC7f33aygf7OG2Zo%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA73QKITUUFE7GD54BGVIOLSEA72XANCNFSM4I4SKCWQ&data=02%7C01%7Cjhalleux%40microsoft.com%7C0fb4b647ad6845978a6408d85072ae90%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637347800775155327&sdata=aVlno1baWgm%2FuN1gg2vvO3IALamhq2mnT9nuvq5UVm4%3D&reserved=0>.

hmmm but we can't pass in an array to a function, so it might not be a useful function?

**Comment by abchatra** [comment]
This API is deviating from the JavaScript. But I see the usefulness of this in the blocks context in the examples. 
Our randomRange is awkward that it includes inclusive of the last parameter (Javascript random is just 0-1 and not inclusive of 1).  Hence you had to substract 1 for the workaround which made the existing solution quite long. (We deviated from spec for randomRange)

I am ok adding this for blocks if it helps in these scenarios.  
Don't add symmetric API to delete a random index after get. It is usually bad practice to delete random things.

**Review by darzu — APPROVED** [review]

**Pull request merged**
