### PR TITLE
Don't include marked.min.js

### PR DESCRIPTION
**Pull request by samelhusseini**
Marked is already required in the main app. No need to add it include it

### CODE REVIEW

**Comment by pelikhan** [comment]
Is it bundled in pxtembed.js?

**Comment by samelhusseini** [comment]
Probably not, what's it used for in pxtembed?

**Comment by pelikhan** [comment]
Embed.js is used in docs right? We need to trace all the place where markdown is used.

_____________________________

**Comment by samelhusseini** [comment]
Okay hold off on this PR.

________________________________

**Comment by pelikhan** [comment]
You could refactor the requireMarked to delay load marked (and still work in node.js). Stil this also used in the backend.

**Comment by samelhusseini** [comment]
Closing for now..

**Pull request closed without merging**
