### PR TITLE
Scale screenshots / gifs to display on social media better

### PR DESCRIPTION
**Pull request by livcheerful**
fixes https://github.com/microsoft/pxt-arcade/issues/2600

The issue was that Facebook won't show images if they're too small (less than 200x200 px), so I added an optional scaling factor to converting the screenshot image -> PNG and also when we make the gifs. Are we worried about this taking too much storage?

[edit] I had a screenshot that I forgot to share!
image
it's a little blurry still, but I think that's on FB's end not liking pixel art. better than having part of the microsoft logo?

### CODE REVIEW

**Comment by pelikhan** [comment]
Storage may or may not be an issue. What kind of size increase are you seeing? Looks good otherwise.

**Review by pelikhan — APPROVED** [review]

**Comment by livcheerful** [comment]
> Storage may or may not be an issue. What kind of size increase are you seeing? Looks good otherwise.

It'll increase by a factor of 3 for all screenshots/gifs

**Comment by pelikhan** [comment]
There is definitely a maximum size. Did you hit with this new change?

________________________________

**Comment by livcheerful** [comment]
oh you're totally right it hit the limit! I changed it so that gifs only scale by 2, which will look like this on FB:

image

**Pull request merged**
