### PR TITLE
tooltip hides on very small screens so it doesn't get cut off

### PR DESCRIPTION
**Pull request by emoltz**
https://github.com/microsoft/pxt-microbit/issues/3130

### CODE REVIEW

**Comment by emoltz** [comment]
@microsoft-github-policy-service agree [company="{ethan shafran moltz}"]

**Comment by emoltz** [comment]
@microsoft-github-policy-service agree

**Comment by jwunderl** [comment]
Hey, thanks for the pr!

I took a look at it and it doesn't appear to fully solve the issue :( the download toolbar is currently switching to the mini-icon only mode for mobile and tablet dimensions (basically, any screen <= 991px), so the issue remains for those (e.g. this is at 990px width): 

image

and it looks like the dimensions that this would affect (< 500px) already have the pop up hidden / not show up, so this wouldn't change that behavior unfortunately. I think ideally the fix for this would either cap the width of the tooltip so it stays fully in screen, or shift it over so it's `left` / `right` are always at least 0 (while still keeping the arrow in the correct position).

**Comment by emoltz** [comment]
So sorry, meant to just draft a PR. I will complete this and get back to you!

**Pull request closed without merging**
