### PR TITLE
Transfer include fix

### PR DESCRIPTION
**Pull request by pelikhan**
Back porting changes to the transfer.html page.

### CODE REVIEW

**Comment by abchatra** [comment]
What does this do? I am confused.

**Comment by pelikhan** [comment]
It imports scripts from a previous domain.

**Comment by abchatra** [comment]
What does this change do?

**Comment by pelikhan** [comment]
Rewriting is not enabled fo transfer.html so doccdn is not resolved.

________________________________

**Comment by riknoll** [comment]
Why did you remove all the CSS? I'm fine with that hardcoded URLs as long as we are planning to kill this page eventually.

**Comment by pelikhan** [comment]
It was already referenced and we are killing this page.

________________________________

**Pull request closed without merging**
