### PR TITLE
Fix TS (gray) blocks, making them multi-lined

### PR DESCRIPTION
**Pull request by microsoftsam**
screen shot 2017-09-20 at 10 41 56 pm

### CODE REVIEW

**Comment by pelikhan** [comment]
I think it's a mistake to show the entire content of the grey block. It's giberish for the kids anyway. We should just do a single line and ...

There are extra new lines that bloat the size of that block.

**Comment by microsoftsam** [comment]
There are no extra lines.. The new rendering has a larger gap between lines. 
As for how to collapse it. I'm okay coming up with a way to collapse the block. but I wouldn't just do a blatant ellipsis. I think you could collapse functions like: "function test() { ... }" but not some blocks might make sense, if they're just simple function calls with parameters perhaps

**Comment by pelikhan** [comment]
With such new line sizes, these grey blocks are going to be huge.

**Comment by microsoftsam** [comment]
Agreed. For now the it looks much worse on the same line. Let's push this in, and discuss an alternative solution for the gray blocks.

**Comment by pelikhan** [comment]
If you pull in some long piece of code, you'll end up with massive greyblocks. I think it is worse than a single line with a guaranteed reasonable height.

**Comment by abchatra** [comment]
@pelikhan  I don't understand your concern. This is for someone who has written code in javascript and compiling back to blocks. I am fine with showing the same code with the same indentation. Are we adding any extra padding?

**Comment by pelikhan** [comment]
The problem is not passing. It is that Scratch blocks add a huge gap between lines.

**Pull request merged**
