### PR TITLE
Revert merge

### PR DESCRIPTION
**Pull request by riknoll**
https://github.com/microsoft/pxt/commit/13d0cb389c717a92276c14319d04d9662380aa15 Accidentally reverted a bunch of changes on master.

Reverting back to the minor bump before that change, and then re-cherrypicking the three commits that came afterwards:
1. 2bb67b590052ec0b96237d7ba6da9bc0c269435f
2. 80833d6f365bdc6fb8bdd1a77f2c1b2eaec06db8
3. e82ba342119f9222953983445c5a69bcb3f9cc11

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]

**Review by shakao — APPROVED** [review]

**Comment by riknoll** [comment]
Since this is hard to review, here are the exact commands I ran:

```
git checkout origin/master -b revert-merge
git checkout 948388b641d889a636fff9cf34c67d343a3c7bd2 -- .
git commit -m "Reverting back to 948388b641d889a636fff9cf34c67d343a3c7bd2"
git cherry-pick 2bb67b590052ec0b96237d7ba6da9bc0c269435f
git cherry-pick 80833d6f365bdc6fb8bdd1a77f2c1b2eaec06db8
git cherry-pick e82ba342119f9222953983445c5a69bcb3f9cc11
```

**Review by pelikhan — APPROVED** [review]
Thanks Richard!

**Review by abchatra — APPROVED** [review]

**Comment by pelikhan** [comment]
will you manually put the minor version afterwards? need to skip 6.11.2

**Comment by riknoll** [comment]
@pelikhan will do

**Comment by riknoll** [comment]
https://github.com/microsoft/pxt/pull/7966

**Pull request merged**
