### PR TITLE
Use tile id if no display name present

### PR DESCRIPTION
**Pull request by shakao**
fixes https://github.com/microsoft/pxt-arcade/issues/3018

the tilemap extension doesn't have display names for tiles and it was filling in eg assets.tile\`tiles.util.door2\` which is not a real tile

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]
LGTM but I prefer parentheses if possible :)

**Review by livcheerful — APPROVED** [review]

**Review by riknoll — CHANGES_REQUESTED** [review]
This should check the prefix of the qname instead of always defaulting to inserting the ID. If it starts with the "myTiles" namespace, it should use the short id

**Comment by riknoll** [comment]
maybe should fix this function to return undefined or something: https://github.com/microsoft/pxt/blob/master/pxtlib/tilemap.ts#L1498

**Comment by riknoll** [comment]
Wait, I'll unify the code for this in my PR

**Pull request closed without merging**
