### PR TITLE
Add support for "hex `01FF00`" - Buffer literals

### PR DESCRIPTION
**Pull request by mmoskal**
This might be useful if we want to embed some data in sources - compact representation in sources and doesn't take any RAM (literals go into flash)

```
const sound = hex `FE01DD...`
```

Whitespace is allowed in the hex literal.

### CODE REVIEW

**Comment by pelikhan** [comment]
@mmoskal  Any chance to fix this PR?

**Comment by pelikhan** [comment]
@mmoskal i can't seem to get this syntax to work

**Comment by mmoskal** [comment]
@pelikhan did it work in the end?

**Comment by pelikhan** [comment]
Yup it is working.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
