### PR TITLE
stable5.15: un-lexically nest function

### PR DESCRIPTION
**Pull request by jwunderl**
cherry picking https://github.com/microsoft/pxt/pull/5758 to fix https://github.com/microsoft/pxt-microbit/issues/2237

### CODE REVIEW

**Comment by pelikhan** [comment]
You need to cherry-pick the travis build fix too.

**Comment by abchatra** [comment]
Why the dependency npm version is updated?

**Comment by pelikhan** [comment]
See https://travis-ci.org/microsoft/pxt/builds/559635924?utm_source=github_status&utm_medium=notification

**Comment by jwunderl** [comment]
to fix travis build: transitive dependency started bundling their own types a few days ago, and a weird interaction caused the old version to lose types (looks like they removed the @types from DT)

Change log between the two version is pretty small https://github.com/request/request/blob/master/CHANGELOG.md and the new version is about a year old now
```
v2.88.0 (2018/08/10)
#2996 fix(uuid): import versioned uuid (@kwonoj)
#2994 Update to oauth-sign 0.9.0 (@dlecocq)
#2993 Fix header tests (@simov)
#2904 #515, #2894 Strip port suffix from Host header if the protocol is known. (#2904) (@paambaati)
#2791 Improve AWS SigV4 support. (#2791) (@vikhyat)
#2977 Update test certificates (@simov)
v2.87.0 (2018/05/21)
#2943 Replace hawk dependency with a local implemenation (#2943) (@hueniverse)
v2.86.0 (2018/05/15)
#2885 Remove redundant code (for Node.js 0.9.4 and below) and dependency (@ChALkeR)
#2942 Make Test GREEN Again! (@simov)
#2923 Alterations for failing CI tests (@gareth-robinson)
```

and some dependency bumps (which is what fixed the build error here)

**Comment by abchatra** [comment]
looks godo

**Pull request merged**
