### PR TITLE
Add tooltip support in React

### PR DESCRIPTION
**Pull request by samelhusseini**
Add support for tooltips on elements. 
Using react-tooltip: https://github.com/wwayne/react-tooltip (MIT)

Note: We need to file an OSS request for this.

### CODE REVIEW

**Comment by pelikhan** [comment]
What is the default delay?

**Comment by pelikhan** [comment]
This is very nice. We could/should add a hinting engine to the tutorial that uses those tooltips. Can you trigger them programmatically?

**Comment by samelhusseini** [comment]
Yes you can trigger programmatically and the interface I added here is probably not the best, we'd have to play around and see how we want to use it. Will keep adjusting as we add more features.

**Comment by samelhusseini** [comment]
Filed OSS request and Approved. We're good to go.

**Comment by samelhusseini** [comment]
Default delay is 0. We can change that in our module.

**Comment by samelhusseini** [comment]
This is ready to go in. @pelikhan can I get a final review?

**Comment by pelikhan** [comment]
Looks good. where do we plan to add those?

**Pull request merged**
