### PR TITLE
Mutators

### PR DESCRIPTION
**Pull request by pelikhan**
Refactoring support for mutators

### CODE REVIEW

**Comment by pelikhan** [comment]
@riknoll this change is roting. We should get it in and solve the rest issue later. Are there annontation changes needed on the .ts radio project?

**Comment by riknoll** [comment]
Yeah, I'll open a PR. One line change.

**Comment by riknoll** [comment]
@pelikhan this should be good to merge

**Comment by riknoll** [comment]
@pelikhan just pushed one commit to fix the code card bug I mentioned earlier

**Pull request merged**
