### PR TITLE
[stable6.0] disable oauth in pxt electron

### PR DESCRIPTION
**Pull request by jwunderl**
port #7130 to stable

### CODE REVIEW

**Comment by jwunderl** [comment]
@abchatra Also need this one to hide crowdin translate editor button

**Comment by abchatra** [comment]
What is the issue with translate? It opens in browser right?

**Comment by jwunderl** [comment]
The redirect link will likely be wrong / not load you in correctly, and the electron app will freeze on the open authentication page. (refreshing won't help, have to close and reopen)

**Comment by abchatra** [comment]
There is a close button at the crowdin login page (kind of hidden). Did you try that?

**Comment by jwunderl** [comment]
Yeah, that's just getting to refreshing the page currently in the app: 

stuck-in-translation

Hm actually don't know if I've checked that in the browser to confirm it's electron only bugginess

**Comment by abchatra** [comment]
change looks good to me. If it is not working, we don't want to fix it for offline.

**Pull request merged**
