### PR TITLE
Enable high contrast styles for skillmap

### PR DESCRIPTION
**Pull request by shakao**
adds high contrast styles, adds settings item to toggle, hooks it up to the main editor high contrast (which is already all nicely piped through the auth service thanks to eric & vivian's work haha)

build: https://arcade.makecode.com/app/4883fe9e2d5a3716f460f3557bf4e7b7eb6fd973-0d61bad887--skillmap

### CODE REVIEW

**Review by riknoll — APPROVED** [review]

**Comment by riknoll** [comment]
hmmm i think the uploadtrg is broken for skillmap

**Comment by abchatra** [comment]
How do I test the skillmap? Following link doesn't open for me. 
https://arcade.makecode.com/app/6642671ff704d47006b60c72bb9c6b276350b0a0-48f7bed654--skillmap

**Comment by shakao** [comment]
ahh hm i wonder if that webpack alias fix for the local build broke the uploadtrg scenario.... let me investigate

**Comment by shakao** [comment]
@riknoll @abchatra fixed build https://arcade.makecode.com/app/4883fe9e2d5a3716f460f3557bf4e7b7eb6fd973-0d61bad887--skillmap

**Comment by abchatra** [comment]
Thanks this link works. 

I think setting high contrast in the skillmap should set high contrast in the iframe as well. Otherwise students have to go to editor and set it there and it is not intuitive.

**Review by jwunderl — APPROVED** [review]
It looks like the 'saving to cloud' got some style leak as it loads as black in non-high contrast mode now: 
image

(vs 
image
)

LGTM besides that & abhijiths point (which should just be loading with `?hc=1` iff high contrast?)

**Comment by shakao** [comment]
@jwunderl nice catch, thanks! i don't want to fully reload the iframe when high contrast is toggled just cause that's kind of disruptive and error-prone, so i'm using messages to pipe that state through

**Pull request merged**
