### PR TITLE
Fixing autocomplete for TS and improving sorting of completions

### PR DESCRIPTION
**Pull request by riknoll**
Fixes https://github.com/microsoft/pxt-minecraft/issues/1725

Also adds an improvement to the sorting of parameter completions where the parameter value is a property access expression. Now we check the return type of the completion entry and weight it higher if it matches.

### CODE REVIEW

**Comment by darzu** [comment]
I noticed we currently have this bug (notice pos and randpos):
image

I wonder if your PR fixes this too?

**Comment by darzu** [comment]
After sleeping on this, I'm leaning towards not including this in the release. It's too much risk, and there will always be another release.

**Comment by darzu** [comment]
Does this PR also fix: https://github.com/microsoft/pxt-minecraft/issues/1769 ?

**Comment by riknoll** [comment]
No, that issue is because of the aliases. We never return positions.random(), only randpos()

**Pull request merged**
