### PR TITLE
Make the block / javascript menu items look like a toggle.

### PR DESCRIPTION
**Pull request by microsoftsam**
screen shot 2016-12-30 at 1 02 11 pm

### CODE REVIEW

**Comment by microsoftsam** [comment]
In mobile view:
screen shot 2016-12-30 at 1 54 25 pm

**Comment by microsoftsam** [comment]
Basic animation: 
toggle_animation

**Comment by pelikhan** [comment]
LGTM

**Comment by Jaqster** [comment]
Yeah, let's get it in Beta and have David review too.

**Pull request merged**
