### PR TITLE
reload in editor if editing on appcache update

### PR DESCRIPTION
**Pull request by pelikhan**
If editor is open with project, reload into that project instead of going to homescreen.

### CODE REVIEW

**Comment by pelikhan** [comment]
Added

**Comment by abchatra** [comment]
Looks good. Thank you Peli for quick fix.

**Comment by pelikhan** [comment]
Good catch

**Comment by pelikhan** [comment]
Not in scope for this fix.

**Comment by pelikhan** [comment]
Still testing do not merge

**Comment by pelikhan** [comment]
Chrome seems to be eating the search section of the URL away when using replace.

**Comment by pelikhan** [comment]
It works because you are changing the URL, but in this case we are changing the hashmark section which does not trigger a page navigation.

**Comment by pelikhan** [comment]
Setting the hash and reloading works for me.

**Comment by pelikhan** [comment]
@guillaumejenkins ready for review

**Pull request merged**
