### PR TITLE
Labs landing page

### PR DESCRIPTION
**Pull request by pelikhan**
Initial stab at a "labs" landing page. It is fairly well hidden from the landing page. We'll need to discuss how we want to hint at user on makecode.com that there are labs avaiable.

image

### CODE REVIEW

**Comment by Jaqster** [comment]
Wow!  That's really green!

**Comment by pelikhan** [comment]
I purposely made it VERY VERY different from the landing page to make sure people don't confuse both. Of course, feel free to change the theme.

**Comment by Jaqster** [comment]
:-)  I like the neon green theme... feels kind of Frankenstein.  But maybe not on the whole body of the page...?  It's a little overwhelming.

**Comment by pelikhan** [comment]
I just want to scare away teachers a bit. All dark was too depressing. Maybe @microsoftsam can add his magic touch.

**Comment by microsoftsam** [comment]
Yeah definitely very green! I like it, can certainly apply my magic touch sometime next week.

**Pull request merged**
