### PR TITLE
New syntax for setting shadow values

### PR DESCRIPTION
**Pull request by riknoll**
Adding some syntax for setting shadow block ids outside of the block string. Hopefully this will make changing shadow blocks without breaking localizations a bit easier. The new syntax overrides the old syntax and I would say the old syntax should be considered "deprecated".

The proposed syntax:

```typescript
//% block="whatever $param=oldShadow"
//% param.shadow="newShadow"
```

Related: https://github.com/Microsoft/pxt/issues/4757

### CODE REVIEW

**Comment by pelikhan** [comment]
Update playground?

**Comment by riknoll** [comment]
Right...

**Comment by riknoll** [comment]
Fixed the playground (also fixed the deprecated % syntax in the block string we were still using)

**Comment by riknoll** [comment]
@pelikhan how do I update pxt-core for the playground? Is that a separate step?

**Pull request merged**
