### PR TITLE
Surface decompilation errors in monaco editor

### PR DESCRIPTION
**Pull request by pelikhan**
Proper diagnostics is generated by the decompiler but not shown to the user. This change surfaces them so that the user has a chance to understand why it does not decompile.

seeconversionerrors

### CODE REVIEW

**Comment by abchatra** [comment]
Can we wait this to go in a separate post BETT branch? Not necessary for BETT right?

**Comment by pelikhan** [comment]
Yup can wait.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
Merged in develop.

**Comment by microsoftsam** [comment]
Closing this PR since this has been merged into develop.

**Pull request closed without merging**
