### PR TITLE
Hit cloud for gh endpoints on localhost

### PR DESCRIPTION
**Pull request by riknoll**
https://github.com/Microsoft/pxt/pull/4708 broke some requests on local serve because we never implemented the endpoints in the development server. Rather than duplicate them in PXT, hit the cloud instead.

### CODE REVIEW

**Comment by mmoskal** [comment]
Maybe it would be better to set `apiRoot` to `https://makecode.com/api/` on localhost and to `/api/` otherwise? It would also simplify this: `${pxt.Cloud.isLocalHost() ? "https://makecode.com" : ""}/api/translations?lang=...`

**Comment by riknoll** [comment]
But wouldn't that hit the cloud for everything?

**Comment by mmoskal** [comment]
You generally want to do that, since there is very few APIs implemented in the local server. I think that was the behavior before that PR. There are some localhost-specific APIs, but these are accessed not via `apiRoot`.

**Comment by riknoll** [comment]
Ah, I see that now. I was worried about breaking the file workspace but you're right. Updated!

**Pull request merged**
