### PR TITLE
Add rename button

### PR DESCRIPTION
**Pull request by sae220**

### CODE REVIEW

**Comment by riknoll** [comment]
@sae220 can you include screenshots of what this flow looks like? or maybe a gif?

**Comment by sae220** [comment]
@riknoll 
header-action
addRenameButton_1
addRenameButton_2
addRenameButton_3
menuitem
addRenameButton_4
addRenameButton_5
addRenameButton_6

**Comment by riknoll** [comment]
@sae220 I really like having this in the "all projects" view, but I'm not so sure about including it in the gear wheel of the editor given that the title is already available in the bottom bar. Is there something not obvious about the current way of renaming projects?

**Comment by sae220** [comment]
@riknoll In the editor in Minecraft Education (not on browser), the bottom bar doesn't appear (I don't know why).
And I think the fileNameInput in the bottom bar is not intuitive, because it looks like for GitHub.

**Comment by riknoll** [comment]
@sae220 I'll bring this up with the team and let you know

**Comment by riknoll** [comment]
@sae220 talked it over with the team, and I think we're all in agreement on the rename button in the "my projects" page being a great improvement.

The other one in the settings menu requires a bit more discussion. Any chance you could split this into two PRs?

**Comment by sae220** [comment]
@riknoll OK, I'll get it done today.

**Pull request closed without merging**
