### PR TITLE
checking for file sizes in docs

### PR DESCRIPTION
**Pull request by pelikhan**
Don't allow files > 5Mb in docs, flag any file > 1Mb.
image
- [x] checking "docs" in checkdocs (5mb max)
- [x] checking files in upload (15mb max)
- [x] support for ``.ignorelargefiles`` to avoid checking particular folders

### CODE REVIEW

**Comment by riknoll** [comment]
We probably need to add an ignore flag just in case we do need to check in a large file at some point. Maybe a pxtarget option to ignore a directory.

**Comment by pelikhan** [comment]
A large file would crash the cloud regardless where it is.

**Comment by pelikhan** [comment]
You can drop a ".ignorelargefiles" to skip a folder

**Comment by pelikhan** [comment]
```
  node_modules\pxt-core\webapp\public\blockly\blockly_compressed.js - 1.065405Mb
  node_modules\pxt-core\built\web\main.js - 9.712638Mb
  node_modules\pxt-core\built\web\pxtapp.js - 1.379336Mb
  node_modules\pxt-core\built\web\pxtblockly.js - 1.793816Mb
  node_modules\pxt-core\built\web\pxtembed.js - 9.764176Mb
  node_modules\pxt-core\built\web\pxtworker.js - 7.454393Mb
  node_modules\pxt-core\built\web\typescript.js - 5.510425Mb
  node_modules\pxt-core\built\web\vs\editor\editor.main.js - 4.824054Mb
  node_modules\pxt-core\built\web\vs\language\typescript\lib\typescriptServices.js - 1.48665Mb
  node_modules\pxt-core\built\web\vs\language\typescript\src\worker.js - 1.556907Mb
```

**Pull request merged**
