### PR TITLE
fix scroll in safari microsoft/pxt-arcade#4097

### PR DESCRIPTION
**Pull request by jwunderl**
fix https://github.com/microsoft/pxt-arcade/issues/4097

### CODE REVIEW

**Comment by shakao** [comment]
it looks like in arcade v1.5 this selector https://github.com/microsoft/pxt/blob/master/theme/themes/pxt/modules/modal.overrides#L48 had `position: relative !important;` on it, could we restore that instead of changing it on the base modal?

**Comment by jwunderl** [comment]
Hmm I can move it to position: absolute there yeah? It looks like some deep changes in sui cause position: relative to break position even more

**Comment by shakao** [comment]
sure, that sounds good to me!

**Comment by shakao** [comment]
does it need the !important? or is it fine with the new styles

**Comment by jwunderl** [comment]
It works fine in the safari devtools, it's overriding the .ui.modals selector just below so this selector is more specific~

**Review by shakao — APPROVED** [review]

**Pull request merged**
