### PR TITLE
Update 'tutorials' page for new block sections

### PR DESCRIPTION
**Pull request by ganicke**
Add some info for the additional block section types.

RE: https://github.com/microsoft/pxt-minecraft/issues/1254

### CODE REVIEW

**Comment by shakao** [comment]
Right now the documentation for "ghost" and "template" are with the other macros: https://makecode.com/writing-docs/macros -- should we consolidate the tutorial-specific macros somehow? 

Hint documentation is currently lumped with "activities" and "steps" here: https://github.com/microsoft/pxt/blame/master/docs/writing-docs/tutorials.md#L232 maybe we should remove it from that section entirely, if we want it in the "Using blocks" section?

**Comment by ganicke** [comment]
@shakao thanks for the comments. This is really a matter of how to message use of hints...blocks themselves are implicit hints but they're blocks too and are related to the template and ghost blocks when discussing usage. The 'reference' for the types are in ``macros.md`` but the discussion of use in ``tutorials.md``? What do you think?

**Comment by shakao** [comment]
Oh yeah, that distinction makes a lot of sense--in that case, LGTM!

**Comment by ganicke** [comment]
We'll keep iterating on this page. It will need some shuffling of structure probably.

**Pull request merged**
