### PR TITLE
moving refcounting in runtime to recycle between runs

### PR DESCRIPTION
**Pull request by pelikhan**
We were leaking refcounted objects in the simulator. Moving ref counting in the runtime state.

### CODE REVIEW

**Comment by pelikhan** [comment]
This fix might need to go in v0 too.

**Comment by mmoskal** [comment]
Looks good!

**Comment by microsoftsam** [comment]
So this breaks the simulators in SIM only targets.

VM51526:1 Uncaught TypeError: pxsim.noRefCounting is not a function
    at eval (eval at Runtime (pxtsim.js:4220), <anonymous>:1:7)
    at new Runtime (pxtsim.js:4220)
    at run (pxtsim.js:1928)
    at receiveMessage (pxtsim.js:1886)

There's a dependency on pxsim.noRefCounting as emitted by the emitter: https://github.com/Microsoft/pxt/blob/a5c9cf0acf8a4d369c1f68d4bc53a86e8605df42/pxtcompiler/emitter/backjs.ts#L67

**Comment by pelikhan** [comment]
Can you file it on me?

**Comment by microsoftsam** [comment]
I can do better, is this the right fix? https://github.com/Microsoft/pxt/pull/3506

**Pull request merged**
