### PR TITLE
Update skillmap build to support versioned skillmap

### PR DESCRIPTION
**Pull request by shakao**
new flow!
- `gulp skillmap` in pxt to copy all files to the correct locations. this:
   - builds the skillmap
   - copies the index.html into `webapp/public` as `skillmap.html`
   - copies the built js and css into `built/web/skillmap`
- build locally by running `pxt skillmap --serve` in the target directory
- the previous build command (`pxt skillmap` in the target) is still around in case we need to deploy before we swap over to the new url

changes:
- all skillmap assets are now permanently kept in `docs/static/skillmap`
- added npm prebuild and postbuild commands to generate an index.html formatted to our specifications (don't remove comments, don't collapse whitespace), so the backend replacements should all work
- added the skillmap url to the webconfig

for https://github.com/microsoft/pxt-arcade/issues/2584

### CODE REVIEW

**Review by pelikhan — CHANGES_REQUESTED** [review]
Please add build instructions to the read me.

**Comment by pelikhan** [comment]
Does the pxt ci run gulp skillmap as part of the build?

**Comment by shakao** [comment]
yep! although it doesn't have to, i can take it out for now since the backend route changes aren't in either

**Review by riknoll — APPROVED** [review]

**Review by jwunderl — APPROVED** [review]

**Comment by riknoll** [comment]
@pelikhan can you mark your changes as resolved?

**Review by pelikhan — APPROVED** [review]

**Comment by riknoll** [comment]
thanks!

**Pull request merged**
