### PR TITLE
Pin lookup fix

### PR DESCRIPTION
**Pull request by pelikhan**
Use the gpiomap to lookup pins in breadboarding.

### CODE REVIEW

**Comment by samelhusseini** [comment]
Did you intend to make boardDef a required field?
That would require target changes namely here: https://github.com/Microsoft/pxt-adafruit/blob/master/sim/dalboard.ts#L176 to pass in the boardDef if it's now required.

**Comment by pelikhan** [comment]
Yes it is mandatory right now but I could make it more resilient if missing.

**Comment by pelikhan** [comment]
It is there, just needs to be passed along.

**Comment by samelhusseini** [comment]
Yeah, its an easy fix in the target, just checking whether it's required now.

**Pull request merged**
