### PR TITLE
Update node-forge to 1.3.1

### PR DESCRIPTION
**Pull request by dmonroym**
Fixes
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/119762/alert/6790960?action=ContributedHub&controller=Apps&typeId=795877
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/119762/alert/6790961?typeId=795877
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/119762/alert/6790959?typeId=795877
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/119762/alert/6329827?typeId=795877
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/119762/alert/6362953?typeId=795877
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/119762/alert/6350317?typeId=795877
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/119762/alert/6350318?typeId=795877
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/121300/alert/6790465?typeId=1649196
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/121300/alert/6790466?typeId=1649196
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/121300/alert/6361513?typeId=1649196
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/121300/alert/6326990?typeId=1649196
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/121300/alert/6790464?typeId=1649196
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/121300/alert/6348861?typeId=1649196
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/121300/alert/6348862?typeId=1649196

Related to https://github.com/microsoft/pxt-backend/issues/587

### CODE REVIEW

**Comment by dmonroym** [comment]
@riknoll for learning purposes, is this what you're talking about? https://github.com/microsoft/pxt/blob/master/skillmap/webpack.config.override.js

Interestingly doing this change locally after removing node_modules gave me this output thinking this compiled succesfully:
```
dmon@dmon-comp MINGW64 /g/makecode/pxt/skillmap (dmonroym/node-forgeSkillmap)
$ npm install

added 231 packages, removed 733 packages, changed 567 packages, and audited 1401 packages in 2m

139 packages are looking for funding
  run `npm fund` for details

6 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

dmon@dmon-comp MINGW64 /g/makecode/pxt/skillmap (dmonroym/node-forgeSkillmap)
$ npm run build

> skillsmap@0.1.0 build
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  126.29 kB (+90.88 kB)  build\static\js\main.241964e7.js
  4.36 kB (-26 B)        build\static\css\main.b82edbf6.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment
```

After swtiching branches and re-deleting node_modules gives me the same build error. I'll try updating the node-forge package by itself

**Comment by riknoll** [comment]
yes, the actual patching is done here:

https://github.com/microsoft/pxt/blob/master/gulpfile.js#L575

**Comment by eanders-ms** [comment]
Note there is no actual vulnerability here. There must be an exception process for dev dependencies. This seems "ok" to me, but I defer to Richard.

**Comment by riknoll** [comment]
My guess is that this upgrade won't cause any issues, but I agree that this is a frivolous vulnerability that doesn't impact any users. We should investigate if there is any sort of exception process for vulnerabilities in dev dependencies that don't ship with the product.

**Comment by dmonroym** [comment]
We can dismiss those alerts by selecting "Component has been misidentified as a dependency" but that will just cause the alert to reappear every time we run the pxt-electron pipeline.

image

**Comment by dmonroym** [comment]
@eanders-ms @riknoll y'all ok to merge this or should I just tag it as misidentified?

**Comment by riknoll** [comment]
sure

**Review by riknoll — APPROVED** [review]

**Pull request merged**
