### PR TITLE
Pick changes from e2ed641

### PR DESCRIPTION
**Pull request by ganicke**
Merge changes from https://github.com/Microsoft/pxt/pull/4345

### CODE REVIEW

**Comment by samelhusseini** [comment]
We typically use functions instead of lamda in master. Moved away from the direction in v0, and making the syntax closer to JavaScript.
 
Not sure if this doc page is supplementary, because users can still use it lamda, but that's not the recommendation. 

@pelikhan @riknoll

**Comment by ganicke** [comment]
You mean stay away from both the arrow syntax and any reference to 'lambda'?

**Comment by ganicke** [comment]
What terms are we using: callback, delegate, handler?

**Comment by samelhusseini** [comment]
Yeah I'm not sure on the best thing to do here, but if our snippets and our recommendation paste in a function handler rather than an arrow function, then our docs should be consistent. 

You can still add a reference to a lamda function (arrow function) page since it still works. 

@pelikhan thoughts?

**Comment by riknoll** [comment]
Callback is definitely the most javascript-y of those but I think our codebase and jsdoc usually use handler

**Comment by pelikhan** [comment]
Move the arrow functions to the bottom.

**Pull request merged**
