### PR TITLE
Arduino UNO support

### PR DESCRIPTION
**Pull request by mmoskal**
This fixes many things in AVR code gen. In addition:
* make parsing of C++ constants a bit smarter
* adapt to recent codal build system changes (this will be required to build CPX after "merge fest"; once it builds again)
* auto-reconnect in `pxt hidserial`
* allow specifying flash size in pxtarget

### CODE REVIEW

**Comment by pelikhan** [comment]
@mmoskal did you do a sanity check with Adafruit?

**Comment by mmoskal** [comment]
Adafruit doesn't build ATM - merge fest

**Comment by tballmsft** [comment]
@mmoskal - did you check that thumb code gen wasn't affected on an ARM target?

**Comment by mmoskal** [comment]
The thing is that Adafruit doesn't build because of codal issues. Joe promised some tags to have a stable version (we were using branches which is WRONG). Will look into that tomorrow.

**Comment by mmoskal** [comment]
Now tested to verify ARM isn't affected.

**Comment by tballmsft** [comment]
Good to go, @mmoskal?

**Comment by mmoskal** [comment]
Good to go!

**Pull request merged**
