### PR TITLE
Blocks only workspace

### PR DESCRIPTION
**Pull request by microsoftsam**
Simple flag to remove the blocks / javascript toggle (for blocks only workspaces). 

To test: 

in pxtarget set ``appTheme.blocksOnly`` to ``true``

### CODE REVIEW

**Comment by tballmsft** [comment]
Hmm... I was thinking of having no UI element at all. Some reason for keeping the button?

**Comment by microsoftsam** [comment]
No reason to keep the button. I can change that.

**Comment by pelikhan** [comment]
There's probably some arcane ways to still end up on the javascript side but it's probably ok as it is.

**Comment by tballmsft** [comment]
Tested. Thanks, Sam!

**Pull request merged**
