### PR TITLE
cloud sync support

### PR DESCRIPTION
**Pull request by mmoskal**
This adds very preliminary support for syncing user workspace (their scripts) with OneDrive and Google Drive.

Additionally:
* refactor workspace providers (node files, electron files, winrt, browser database) to be simpler - move code to common workspace.ts
* various syncing fixes

### CODE REVIEW

**Comment by mmoskal** [comment]
Test build: https://maker.makecode.com/app/83491c40712374efd8c827d7b09dab60c3090447-d1571b7834#

**Comment by riknoll** [comment]
I'm getting 403s... Does this not work with `@microsoft.com` accounts?

**Comment by mmoskal** [comment]
I thought it did. Investigating.

Works with regular live and google

**Comment by mmoskal** [comment]
All scripts are synced. It's all automatic. All you do is login.

**Comment by mmoskal** [comment]
I think this is too complicated. 

Anyway, this is mostly to merge in the workspace changes. We will still work on the UI sometime in the future, before enabling this anywhere.

**Pull request merged**
