### PR TITLE
Blink tutorial tab dot to draw user attention

### PR DESCRIPTION
**Pull request by shakao**
fix-dot-glow-5

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]

**Comment by livcheerful** [comment]
could....it be a glow pulse? or like a bounce? eric is right this is very recording vibes lol

**Comment by shakao** [comment]
@livcheerful haha hmm good point, thoughts?

fix-dot-bounce 
fix-dot-glow

**Comment by livcheerful** [comment]
omg the SPEED????

hmmmmm what if the glow was white? is that possible?? and I feel like it would feel not recording-y if it was like.....GLOW - wait -wait -wait -wait -wait GLOW? But also am open to other ideas??

**Comment by shakao** [comment]
synced with @livcheerful to come up with a more subtle/less recording-y animation! updated gif:

fix-dot-glow-5

**Review by livcheerful — APPROVED** [review]

**Pull request merged**
