### PR TITLE
YouTube-Embeding as optional feature

### PR DESCRIPTION
**Pull request by Amerlander**
Added an Option to Embed YouTube Videos direct into the CodeCard-Preview:

e.g.:

"youTubeId": "qqBmvHD5bCw",
"embedYouTube": "true"

### CODE REVIEW

**Comment by Amerlander** [comment]
Unfortunately the integration test issues that the iframe uses `sandbox='allow-scripts allow-same-origin'`. But YouTube needs these properties to embed videos. Using no sandbox tag at all would help, but is also not allowed by the integration test.

**Comment by pelikhan** [comment]
We added support for playing .mp4 inline. Is it enough for you?

**Comment by Amerlander** [comment]
Well, using self hosted .mp4 for inline videos could be an option and since it's a more cosmetic change it's okay to have this PR not merged yet.

**Comment by pelikhan** [comment]
YouTube videos are commonly blocked in school networks. With inline hosted .mp4 videos, you don't have this problem (and they are much smaller than gifs). How long are your videos?

**Comment by pelikhan** [comment]
@shakao can we bring back video support?

**Pull request closed without merging**
