### PR TITLE
Fixed NL translation issue

### PR DESCRIPTION
**Pull request by jantielens**
In Dutch "vervangen door" translates to "replace by". I recommend to translate it to "veranderen met".

### CODE REVIEW

**Comment by pelikhan** [comment]
Hi Jan, translations have to fixed in crowdin otherwise they will be overridden. See makecode.com/translate
Thank you!

**Comment by jantielens** [comment]
Hi Peli! Long time no see. :) I've created the request on Crowdin.
Greetings from Belgium,
J

**Comment by pelikhan** [comment]
Long time!!! What is your crowdin alias?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jantielens** [comment]
jantielens (I've signed in with my GitHub account).

**Comment by pelikhan** [comment]
I've made you a proofreader so you should be able to apply the fix directly in crowdin (it will be automatically slurped in the editor after some time)

**Pull request closed without merging**
