### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by abchatra**
https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning

### CODE REVIEW

**Review by riknoll — APPROVED** [review]

**Comment by riknoll** [comment]
will this work on ts?

**Comment by abchatra** [comment]
Should work on ts. Lets see.

**Comment by jwunderl** [comment]
Hmm, I'm getting build failure emails on all pushes to non-master/stable/v* branches from this it looks like:

image

**Comment by abchatra** [comment]
Hmm. It is only setup to run on these branches;  branches: [ master, stable*, v[0-9] ]

**Pull request merged**
