### PR TITLE
Fix compilation with disabled blocks

### PR DESCRIPTION
**Pull request by pelikhan**
It turns out that we treat disabled blocks as events and sort them in the compiler. To create a call key for the block we compile each variable which blows up because the context has not been set.

> This change modifies the blocky compiler to sort events **after** disabled blocks have been filtered out. The only impact I can see here is that the decision to disable a bloc is now dependent on their positions rather than their naming -- **which might be a breaking change**.

Fixed. It uses the previous sorting.

@riknoll @abchatra careful review here

Fix for https://github.com/microsoft/pxt-arcade/issues/1485

### CODE REVIEW

**Comment by riknoll** [comment]
Oh, I see how this could be breaking. Why is it based on positions, though? Can we just sort twice to restore the old behavior?

**Comment by riknoll** [comment]
Hmmmm... I think maybe we should start persisting whether a block is enabled/disabled in the XML. This seems like something we could break again in the future.

**Comment by pelikhan** [comment]
IMO. This is OK. The previous behavior was kind of arbitrary while now it is geometric. Not sure about storing the disabled state in XML since we recompute it on each build.

**Comment by riknoll** [comment]
Right, but we could persist the saved state until the user makes an edit and then recompute it. At least in that case we would prevent shared scripts from breaking.

**Comment by pelikhan** [comment]
Shared scripts don't compile the blocky code; they execute the javascript immediately.

**Comment by pelikhan** [comment]
I'm going to fix this.

**Comment by pelikhan** [comment]
@riknoll ready for review again

**Pull request merged**
