### PR TITLE
Fix regression with blocky checkbox in screenshots

### PR DESCRIPTION
**Pull request by microsoftsam**

### CODE REVIEW

**Comment by microbit-carlos** [comment]
Does this fix the issue with black checkboxes in screenshots?

microbit-screenshot

**Comment by riknoll** [comment]
@microbit-carlos yep!

**Comment by microbit-carlos** [comment]
Great, glad it's already fixed. Is there any ETA on when this might reach the makecode.microbit.org editor?

**Comment by riknoll** [comment]
It's live now at https://makecode.microbit.org/beta

**Comment by microbit-carlos** [comment]
Oh, that's great, thanks @riknoll !

**Pull request merged**
