### PR TITLE
Add a 'licensing' page to the docs guidance pages

### LINKED ISSUE #9069: Update docs to include recommended content licenses
Hi Galen,
Can you update our Writing Docs page to also include a point about Licenses?  https://makecode.com/writing-docs 
We'd like folks who are setting up repositories with tutorials, skillmaps, curriculum, etc. to start using a standard license.
We would like to recommend they use a Creative Commons license - either CC BY, CC BY-SA or CC BY-ND (https://creativecommons.org/licenses).
Thanks!
Jacqueline

### PR DESCRIPTION
**Pull request by ganicke**
This is a base page on recommending the inclusion of a license when creating MakeCode related content. Feel free suggest additional info or any corrections.

Closes #9069

### CODE REVIEW

**Review by Jaqster — APPROVED** [review]
Looks good.  Just made a wording recommendation.

**Comment by Jaqster** [comment]
@abchatra - do you want to take a peek and make sure this looks good?  Also, do we want to include/recommend MIT license for extensions/code?

**Comment by abchatra** [comment]
@ganicke we should only ask following 2 which are allowed for commercial for tutorial content.
CC-BY 4.0 (allows derivatives or adaptations) and CC-BY ND 4.0 (does not allow derivatives or adaptations).

For extensions, today all of them need to be MIT Licensed. We enforce it as extensions are code library which students will use in their project. Micro:bit foundation also enforces it in their documentation.

https://support.microbit.org/support/solutions/articles/19000054952-makecode-extension-and-tutorial-approval
image

**Comment by ganicke** [comment]
@abchatra - thanks for those changes. I've updated the page.

**Pull request merged**
