### PR TITLE
Create an editor toolbox

### LINKED ISSUE #906: Redo and undo buttons don't work on  IE11
Tried in blockly view, both button and right click undo

### LINKED ISSUE #909: Toolbox scrolls on small screens
The undo and add package buttons get cut in half

### LINKED ISSUE #930: Undo button stays blue after being pressed even once mouse leaves it
(Using both /beta and pxt.microbitorg on Chrome on macOS 10.12)

Steps to reproduce
* Drop a block onto the canvas
* Click the undo button
...the action is undone
* Notice that the undo button stays 'blue'
* Interact with the blocks again
...the undo button is coloured correctly

Expected Behaviour:
The undo button turns blue on mouseover, (as currently happens), darkens on click (as currently happens) and then returns to the original state after the undo action is complete or some small animation time (so the colour click is perceptible) afterwards (currently does *not* happen)

### LINKED ISSUE #1042: toolbox issues
- [x] flyout is too transparent and it gets confusing when blocks are under
- [x] search should be hidden in icon mode
- [x] advanced should use ... icon instead of gearwheel
- [x] category name should be used in tooltip in collapsed mode

### PR DESCRIPTION
**Pull request by microsoftsam**
The editor toolbox should encapsulate all the editor specific actions. 
- [x] Show a small toolbox with editor specific actions down the bottom of the screen
- [x] In the mobile view, the editor shares it's space with the simulator. 
- [x] Removed zoom buttons from blockly 
- [x] Removed undo bottom from the blockly toolbox 
- [x] Search hidden in mobile mode 
- [x] Reset grid breakpoints to default, supporting 3 main views: mobile, tablet, and computer
- [x] Collapsable toolbox for tablet and mobile views
- [x] updated projects dialog

Mobile: 
screen shot 2017-01-09 at 12 11 04 am

Mobile collapsed: 
screen shot 2017-01-09 at 12 11 12 am

Tablet: 
screen shot 2017-01-09 at 12 11 23 am

Tablet collapsed: 
screen shot 2017-01-09 at 12 11 29 am

Computer:
screen shot 2017-01-09 at 12 11 39 am

Widescreen: 
screen shot 2017-01-09 at 12 34 19 am

Fixes #1042
Fixes #930
Fixes #909
Fixes #906

### CODE REVIEW

**Comment by pelikhan** [comment]
Looks awesome. What is the speaker button?

**Comment by pelikhan** [comment]
In mobile a bit more bottom and right margin needed. The gray buttons look very dark also. Is that the default color?

**Comment by jaustin** [comment]
I'd love it if these changes could also let me shrink the simulator on Desktop - I love having the simulator there, but I usually don't want to give it as much space as it currently has. (This is added to by the fact that zooming out using the browser does some odd things to block/simulator scale, too)

**Comment by pelikhan** [comment]
Do we really want to surface "redo" in the editor? Once a feature is surfaced, it is harder to remove it. We should understand if there is a need for it in a beginner editor.

**Pull request merged**
