### PR TITLE
Time machine updates

### PR DESCRIPTION
**Pull request by riknoll**
This pr does a few things:
1. New time machine design with a tree view instead of a slider
2. Time machine is now "See Version History" and lives next to the other project things in the cogwheel
3. Reduces the history interval to once every 5 minutes
4. Adds a "save a copy" button to the time machine page

image

image

### CODE REVIEW

**Review by eanders-ms — APPROVED** [review]
LGTM

**Comment by THEb0nny** [comment]
@riknoll I added timemachine to pxt-ev3 and noticed a problem, it can also be seen in arcade. I created a new project and in the change history I see the word Yesterday with the Russian language turned on. I switch to English and it comes out there today. I checked in Crowdin this is not a translation error. the word Yesterday actually comes out there.

**Comment by riknoll** [comment]
hmmmmm... not sure what that could be. the time machine doesn't really pay attention to the locale. i'll try and fiddle with it when i get a chance.

**Comment by riknoll** [comment]
in the meantime, can you file an issue in pxt-arcade and tag me?

**Pull request merged**
