### PR TITLE
rearranging array blocks

### PR DESCRIPTION
**Pull request by abchatra**
Just rearranging the array blocks

### CODE REVIEW

**Comment by pelikhan** [comment]
screenshots?

**Comment by pelikhan** [comment]
How about tweaking the block names to avoid the blank on the left
image

**Comment by abchatra** [comment]
@pelikhan Any suggestions? This is a point fix to go in with Chibi.

**Comment by pelikhan** [comment]
It looks better when there is a word on the left blank section.

________________________________

**Comment by abchatra** [comment]
image

**Comment by abchatra** [comment]
@pelikhan quick sign off please? As discussed other changes will be in a separate work.

**Comment by samelhusseini** [comment]
Also work that should be done in future PRs is ensure all blocks have shadows (we discussed having shadow blocks based on the array type). ie: if it's an array of numbers, show a number field, if it's an array of strings, show a string shadow block. 
Much better than having an empty slot, and it's actually quite clunky having to drag out a string / number block for each one.

**Pull request merged**
