### PR TITLE
Use prod react

### PR DESCRIPTION
**Pull request by samelhusseini**
Use the production version of react on prod builds (travis)
As per https://reactjs.org/docs/optimizing-performance.html#use-the-production-build

### CODE REVIEW

**Comment by pelikhan** [comment]
Cherry pick to v0. Does uglify  destroy stack trace in prod?

**Comment by samelhusseini** [comment]
According to the react docs, the only thing you're losing is "helpful" react warnings that are useful in development but should be taken out of production. so that doesn't include errors.

**Comment by samelhusseini** [comment]
and nothing about a stack trace.

**Comment by samelhusseini** [comment]
Also, note I'm not actually uglifying the code. There's one more step that we could do to actually uglify and minify the code, but that would make debugging the prod site much harder without sourcemaps (maybe something to look into down the track). 
I'm only doing the first two steps recommended by React to strip out unused code and debugging warnings.

**Pull request merged**
