### PR TITLE
use a symlink to link to docs for multiplayer/skillmap build

### PR DESCRIPTION
**Pull request by jwunderl**
a little bit nicer to not have to wait for all of our docs folder to get copied over (twice for everything in static) when serving multiplayer / skillmap, and also makes it so you can do local testing of skillmap files without constantly reserving. Also removes requirement to have `--docs .` when serving multiplayer

note the 'junction' param, normal symlinks for dirs get blocked in node because they are deemed a security risk (I believe?) and restrict to admin env only.  The important thing to note is that that it's restricted to local paths only, but I doubt that affects anyone? https://stackoverflow.com/questions/9042542

Probably worth getting someone to test this real quick on mac or linux (wsl) real quick? just make sure `pxt multiplayer` looks valid / has the right icons and maybe check that `localhost:3000/?nolocalhost=1#local:skillmap/intermediate-skillmap`, but it looks like skillmap is broken locally for me right now? throws a bunch of errors for me e.g. `Uncaught Error: Invalid hook call. ` with 
image
and also 
image

but this also occurs on master~

### CODE REVIEW

**Comment by eanders-ms** [comment]
I have a fix incoming for `process not defined`, which just started happening in multiplayer. Maybe it will fix things for skillmap.

**Comment by eanders-ms** [comment]
I'm not seeing build errors in skillmap.

Does this mean we'd have to run shells as admin?

**Comment by jwunderl** [comment]
no, "junction" type is runable on normal cli, it is "dir" type that requires admin.

**Comment by jwunderl** [comment]
This code was refactored away / pr no longer relevant

**Pull request closed without merging**
