### PR TITLE
Always reload into home screen.

### PR DESCRIPTION
**Pull request by samelhusseini**
Always reload into the home screen.

If we had to choose between one and the other, home screen is safest.

Fixes https://github.com/Microsoft/pxt/issues/3459

### CODE REVIEW

**Comment by samelhusseini** [comment]
Reloading into home when in home. I see no reason to use another tag. We only need one for the editor. Otherwise default to home.

**Comment by pelikhan** [comment]
Do we have a tick for editor reloads?

**Comment by samelhusseini** [comment]
Doesn't look like it.

**Comment by samelhusseini** [comment]
@guillaumejenkins?

**Pull request merged**
