### PR TITLE
Fix WindowsRT download

### PR DESCRIPTION
**Pull request by pelikhan**
This PR fixes download in Windows10 app. Tested also that webusb still works. The heart of the issue was that we running cmds.init before configurating DAPLink.

- [x] disable webusb in electron
- [x] rename mk*PacketIOAsync to relevant names to help with stacktraces
- [x] removed drive deployment in WinRT - this is dead code.
- [x] ignore .simstate.json conflict state
- [x] initialize commands **after** loading extensions -- since micro:bit loads DAP extension.
- [x] always disconnect before running cmds.init
- [x] avoid ping2s animation, does not work in Edge

### CODE REVIEW

**Comment by abchatra** [comment]
Will review. Probably you need to test Adafruit app with these changes.

**Comment by abchatra** [comment]
Also big thank you!

**Comment by pelikhan** [comment]
Adafruit mostly works. There is some weird error after flashing in winrt but mostly it works. This will need to be revisted when Adafruit gets upgraded.

**Comment by abchatra** [comment]
I think this broke serial data from the webusb. It doesn't work always now and very spotty.

**Comment by abchatra** [comment]
Above may be a false alarm. I can't find a repro.

**Pull request merged**
