### PR TITLE
Tutorial tinker

### PR DESCRIPTION
**Pull request by pelikhan**
Tinkering with various simplifications and improvement to the tutorial experience: 
- [x] removing icon button: the "hint" term bleeds out in many locales, and it does not seem to provide any incentive for users to click it
- [x] while a research says that a dialog like rendering makes it more likely to be read, the current rendering does not really work. removing for simplicity and space.
- [x] expanded mode that allows to see most of the hint and the code.
- [x] added "More..." button to expand hint aread to 20rem (or more), "Less..." button to collapse.
- [x] show back button (it is used)

Updates:
- [x] fixed font
- [x] hide next/back in smaller screens
- [x] shrink size of block snippets when large
- [x] keep details opened if full screen dialog
- [x] don't use lightbox, use fade left/right animation
- [x] better support for thin screens
- [x] no-select on text
- [x] hide screenshot button
- [x] redraw next/previous buttons

known issues
- [x] crazy scrolling issues on iOS

### CODE REVIEW

**Comment by riknoll** [comment]
Nice! One less modal!

Some UI comments:
1. I think we should do what David mentioned and make the hint-area only go over the editor workspace and not the toolbox. The editor changing shape is less jarring than the toolbox.
2. The "More" button takes up a lot of vertical space. Maybe we could do a thinner drawer handle like we do with the sidedocs? Horizontal and not vertical though
3. We should stop using the target font-family for the hint text. It's especially bad in arcade because it's monospace; it looks cute on buttons but it really stretches out text. That will free up even more real estate

**Comment by pelikhan** [comment]
1. The first toolbox categories are going to be orphaned on the upper left when the hint area becomes very tall. I don’t think that works.
2. Button is big but they may be a good thing. Eg obvious possible action.

**Comment by riknoll** [comment]
2. The button can be big, but it shouldn't mean we lose 30% of the hint area with whitespace

**Comment by pelikhan** [comment]
The hint area is fixed size so you’ll get some blank on short instructions. I can try the smaller sizes of buttons later.

**Comment by jwunderl** [comment]
Went through a tutorial in the iPad air 2 simulator, seemed like a much better experience than the current tutorials on there (would have to test on a real one to verify).

Minor visual bug w/ block snippets going outside of borders:

Screen Shot 2019-04-15 at 9 01 54 PM

Spacing looks better / can actually read many steps entirely in 'less' mode:

Screen Shot 2019-04-15 at 9 07 04 PM

I do think I like the side docs style more / less button handles; some of the instructions hid the more button entirely due to the length of the instruction (e.g. the previous image), and having it as a handle keeps it consistent

**Comment by pelikhan** [comment]
One could argue that hiding the "more..." button is a feature, it forces people to read the instructions. I can see how it gets annoying.

We should also hide those "next", "previous" text on ipad.

**Comment by pelikhan** [comment]
The other thing that looks promising is using animation to highlight transitions between steps (instead of the lightbox)

**Comment by shakao** [comment]
I messed around on your demo link a little to mock up a possibility with the hints over the editor area and the toolbox flyout going over the hints: 

tutorial

I think it does feel smoother to have toolbox fixed while the editor shrinks, but it's a little busy where the flyout overlaps the hints.

**Comment by pelikhan** [comment]
Try an iPad view...

________________________________

**Comment by pelikhan** [comment]
I think it works well in the wide desktop view (that you are using) but we need the horizontal space for smaller screens (eg iPad landscape/portrait  mode). Might be something to do based on the screen size.

**Comment by shakao** [comment]
iPad landscape:
tutorial-ipad

Hmm yeah, I see what you mean. It looks okay in iPad portrait when the simulator is below, but it's kind of crowded here. Changing it based on screen size seems reasonable to me

**Comment by pelikhan** [comment]
The first category of the toolbox is right next to code canvas. Putting the instructions on the code canvas itself breaks this (and loose precious horizontal space).

I think there is too much size changes right now. I might just keep it expanded.

**Comment by riknoll** [comment]
I think the more/less button should be fixed and not part of the scrollable surface

**Comment by pelikhan** [comment]
More / less could be replaced by an arrow pointing up/down anchored at the center

**Comment by pelikhan** [comment]
Here is a build that does not collapse https://arcade.makecode.com/app/a991e4ca64ceb4f701b41874693119a28d515d94-238cd03e73

**Comment by pelikhan** [comment]
Eventually I’d like to remove most modal dialogs. Maybe we should have the text come in line by line just like in retro dialog games.

**Comment by pelikhan** [comment]
Anchoring the buttons and fixing the font.
https://arcade.makecode.com/app/2059f9d9b18f466ea6cd9ae50f84f7407707beda-fc094a3d8e
tutsize

**Comment by abchatra** [comment]
I tried the build you shared. 

Each step shows all the content instead of showing just the less version of it.  Looks like it is not saving the state of being shorter content (I clicked on more once)

**Comment by abchatra** [comment]
I am not sure this works on chromebook
image

**Comment by pelikhan** [comment]
Currently not saving I was trying out staying in expanded. Do you have the resolution of chrome books?

**Comment by pelikhan** [comment]
Looks like 1024 x 480
image

**Comment by pelikhan** [comment]
Collapses the dialog on each step
https://arcade.makecode.com/app/2da89cd1ce376fa2cc22737a08d73674c11b7d91-8f25b1c639

**Comment by pelikhan** [comment]
For refrence, current tutorial experience at 1024x480
arcade makecode com_(Chromebook (low-end))
arcade makecode com_(Chromebook (low-end)) (1)

**Comment by abchatra** [comment]
Probably topic for design meeting. Can we just keep the _less_ version as default? Students have to click _more_ if they want full hint?

**Comment by pelikhan** [comment]
- [ ] less is default always
- [ ] some size optimization for thin screens

tutsize

https://arcade.makecode.com/app/37f16e0ee8222bc9ebe29917d3b7b85dcb23bd5b-bb93e1933c

**Comment by pelikhan** [comment]
In general, our support for the "thin" view is not stealler. The home screen has definitely usability issues around it. I've made some optimization to the CSS to "reclaim" some space here and there.

tutsize

image

**Comment by pelikhan** [comment]
Somewhat better home experience on thin screens.
tutsize

https://arcade.makecode.com/app/f9b59dc6cbaa01e65b97baa8c9571bf0b5947543-b1169a7af3

**Comment by pelikhan** [comment]
Avoid CSS clashing between mobile and thin.
https://arcade.makecode.com/app/15eaeb98d931e932a4700a72a71d88fc3d45d315-42708e1a2a

**Comment by pelikhan** [comment]
Fixed on ios

**Comment by pelikhan** [comment]
https://arcade.makecode.com/app/e1eae14ab5a40f7d04079ea2bea49e5f41abdfa0-d3b18c2c6f
Ready for review.

**Comment by abchatra** [comment]
Can we make next, back both above or below the carrot?
image

**Comment by pelikhan** [comment]
https://arcade.makecode.com/app/95aa04bd8f0240f830d1a5a1a0ca38b3be768768-12b2c7d081

**Comment by jwunderl** [comment]
Tested on a couple simulators:

iPad Pro 12.9in 3rd generation: no major issues, though I noticed using the sprite editor scrolled the text in the hint (only when it's expanded)



iPad Air 2: Same, looks reasonable to me even in expanded mode

Screen Shot 2019-04-18 at 11 11 30 AM
Screen Shot 2019-04-18 at 11 11 00 AM

iPhone Xr and iPhone Xs: Usable to pretty good in portrait mode:

Screen Shot 2019-04-18 at 11 16 47 AM

broken in landscape (though I'm not sure there is much hope for that every being a great experience?):

xr
Screen Shot 2019-04-18 at 11 18 17 AM

xs



Also, should there be a screenshot button in tutorial mode? Not for / against (and not a change from this PR), just noticed that it seems like a feature that could potentially be cut for the 'streamlined ui' mode

**Comment by pelikhan** [comment]
Yes screenshot should be hidden definitely.

________________________________

**Comment by pelikhan** [comment]
No more screenshot button, no-select on text.
https://arcade.makecode.com/app/c91730eebd2184c65093fa9dfb66f93b3ffcc451-180cb891e3

**Comment by pelikhan** [comment]
Looks like landscape iPhone X is in a trouble zone for our media queries
localhost_3232_index html(iPhone X)
https://arcade.makecode.com/app/c377c966b437112f64a01824857760b3571ccc4f-5fda2759aa

**Comment by jwunderl** [comment]
Not a particularly good situation as is, I don't think there's enough room. Maybe portrait mode only for phone screens in tutorial mode?

**Comment by riknoll** [comment]
Can we just force portrait for our app on all phones? I feel like the editor was not designed to be landscape friendly tutorials or otherwise.

**Comment by abchatra** [comment]
I don't care much about phones. Tablets are the scenario. Folks don't code on phone. It is a consumption device.

**Comment by pelikhan** [comment]
Bigger download button on chrombooks
https://arcade.makecode.com/app/ba15749207ba75af0ab501d72be818b1d7352971-e618c6f92e

**Comment by pelikhan** [comment]
Don't show groups in expanded mode 
https://arcade.makecode.com/app/500ecab8d07248988535842ed7cf9992f9ce1568-c0c6aa114f

**Comment by abchatra** [comment]
@darzu I am not sure why Python changes are going into this PR?

**Comment by pelikhan** [comment]
It's the branch we use for minecraft right now.

**Comment by darzu** [comment]
Yeah, ideally these should have been a separate PR.
Main changes made:
- shorten auto-generated python function names
- omit type annotations for a few cases where the types can be inferred
- bidirectionally snakify & de-snakify the majority of JS <-> PY code

Either someone could take a look at my changes in this PR.
Or, I could still move this to a new PR, it'd just be a bit of work cherry picking and merging.

**Comment by pelikhan** [comment]
I cherry picked them into master already.

**Comment by pelikhan** [comment]
@shakao  can you integrate the changes you did during the design meeting?

**Comment by shakao** [comment]
sure! just to recap, it's:
- orange arrows, no background
- text ("Next") underneath arrow
- hide "Back" arrow(?)

sounds right?

**Comment by pelikhan** [comment]
Yep

________________________________

**Comment by shakao** [comment]
https://arcade.makecode.com/app/ae28cf4baa6567a4e96aaf7047d38b74886b6a6f-c580625ccc

**Comment by pelikhan** [comment]
Very cute.

**Pull request merged**
