### PR TITLE
Create a localization blog post

### PR DESCRIPTION
**Pull request by anzhou5**
Post a blog about helping with translation on Crowdin - "Translation Tips and Tricks".

### CODE REVIEW

**Review by Jaqster — CHANGES_REQUESTED** [review]
Thanks Angel.  I made a few wordsmithing tweaks and also have some comments:
- Add screenshot images to show the 3 different parts of the editor that need to be translated
- Also add a screenshot and a link to a sample task (i.e. https://crowdin.com/project/makecode/tasks/294) or even just specify the name of the file for each of the 3 things that need to be translated
- Add an image or gif of in-context translations

**Comment by anzhou5** [comment]
@ganicke , are there any other files that need to be changed in order to publish this post?

**Review by ganicke — APPROVED** [review]
I added the entry for the blog main page and did a few edits.

**Comment by anzhou5** [comment]
@Jaqster would you mind approving this if the changes you requested have been made to your satisfaction?

**Review by Jaqster — APPROVED** [review]
Looks great!

**Pull request merged**
