### PR TITLE
Bring crowdinStatsCommand back

### PR DESCRIPTION
**Pull request by sae220**
This command is temporarily disabled by @riknoll in #9954 .
I haven't done any testing because I can't use some API with my key.

### CODE REVIEW

**Comment by riknoll** [comment]
ah, @sae220 I actually just opened a PR fixing this! Check it our here:

https://github.com/microsoft/pxt/pull/9962

Interesting that it doesn't work with your API key... do you happen to know which API was failing? what permissions did you give it?

**Comment by riknoll** [comment]
Also, were you using this command? If so, can I ask what for? I might be interested in your use case to see if I could make something more comprehensive for you.

**Comment by sae220** [comment]
Thanks a lot for your great help.

> do you happen to know which API was failing? what permissions did you give it?
SorceFiles API (like List Files). This returns 403 Forbidden. I gave all permissons.

> Also, were you using this command? If so, can I ask what for?
I only did some test to try to solve #9926. I'm sorry that I can't give you interesting use case.

**Comment by riknoll** [comment]
No worries! Thanks for the PR in any case.

I'll have to investigate if Crowdin has a way to get file IDs without list files, it's a really slow request and the permissions on it do seem weird.

**Comment by sae220** [comment]
I asked crowdin support team why I can't access some API. The answer is below.

> Yes, to access all API capabilities you need to be a manager and have a manager token. Also developer role would work

Now I ask ganicke to give me in crowdin conversations.

**Pull request closed without merging**
