### PR TITLE
Bump blockly

### PR DESCRIPTION
**Pull request by livcheerful**
Bump to pull in the fix for https://github.com/microsoft/pxt-microbit/issues/3496

### CODE REVIEW

**Comment by abchatra** [comment]
I reviewed all the changes between these 2 versions and I think they are low risk. @riknoll for a secondary opinion.

**Comment by abchatra** [comment]
@livcheerful I think we should postpone this to a later timeframe. It is too close to the release to update blockly. Keep this PR open, we will discuss post release.

**Comment by livcheerful** [comment]
soooooooounds good!

**Comment by pelikhan** [comment]
No upgrade?

**Comment by abchatra** [comment]
Is this outdated PR?

**Comment by livcheerful** [comment]
ah yes there are better versions to bump to now! I can update

**Comment by abchatra** [comment]
I think we should close this PR for now. We have annual update coming in April for microbit and new blockly will be part of it.

**Comment by livcheerful** [comment]
sounds good!

**Pull request closed without merging**
