### PR TITLE
[stable7.3] More careful patching of user preferences (#8607)

### PR DESCRIPTION
**Pull request by shakao**
* more careful patching of user preferences

* remove variable scoping

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]
LGTM, probably should port https://github.com/microsoft/pxt/pull/8610 too

**Comment by shakao** [comment]
hmm, isn't that fix for non-identity targets?

**Comment by jwunderl** [comment]
Hm doesn't it also apply when the user is just not signed in when sign in is available? 

(either way it would be needed for offline app most likely, but if it doesn't repro in the not signed in case I suppose we could port it later for an offline app only portion)

**Review by dmonroym — APPROVED** [review]

**Comment by shakao** [comment]
yeah i think it's specifically in the case of auth being disabled for the target, not just when the user is logged out. pulled it over for the offline app though! we should remember to thoroughly test language stuff in arcade this afternoon

**Pull request merged**
