### PR TITLE
Lighten or darken border colors for nested same-color blocks

### PR DESCRIPTION
**Pull request by riknoll**
Fixes https://github.com/microsoft/pxt-microbit/issues/4962

Automatically tweaks the block border color when the parent and child are the same color.

image

The results do indeed have better contrast, but do look a bit worse imo.

@Jaqster @microbit-carlos please try out this upload target before I merge:

https://makecode.microbit.org/app/cdb16cf340702c5347c39a1b207988ec2a9bad1c-621f187ad4#editor

### CODE REVIEW

**Comment by Jaqster** [comment]
Thanks Richard!  Is this the right target for this fix?  I think it might be Blocks in Tutorial instructions instead...  
image

**Comment by riknoll** [comment]
@Jaqster this doesn't have anything to do with the tutorial block rendering changes, the linked issue is for blocks in the workspace.

This will affect blocks in tutorial hints though.

**Comment by Jaqster** [comment]
Got it.  I think it looks pretty good to me.  Definitely clearer nesting.  Aesthetically maybe not as nice with all the lines on the blocks, but overall I think readability is worth it.  
microbit-screenshot (9)

**Review by thsparks — APPROVED** [review]
LGTM!

**Review by jwunderl — APPROVED** [review]

**Pull request merged**
