### PR TITLE
Fix page visibility check in app.

### PR DESCRIPTION
**Pull request by samelhusseini**
If we're in an app, don't worry about page visibility check.

### CODE REVIEW

**Comment by pelikhan** [comment]
What about being hosted in iOS?

**Comment by samelhusseini** [comment]
Good question, I don't know how we know that we're hosted in IOS..

**Comment by pelikhan** [comment]
We are in the micro:bit iOS app (upcoming beta)

**Comment by samelhusseini** [comment]
Yes but how can we identify that? (in code)

**Comment by samelhusseini** [comment]
As in UserAgent won't cut it.

**Comment by pelikhan** [comment]
Forget it for now. Might not matter.

**Comment by samelhusseini** [comment]
Okay.

**Pull request merged**
