### PR TITLE
Webusbpairdialog

### PR DESCRIPTION
**Pull request by pelikhan**

### CODE REVIEW

**Comment by mmoskal** [comment]
I guess the logic should be:
```
try to pair
if (connected)
  if (bootloaderMode)
     flash
     pair again
   else
     switch to bootloaderMode
     flash
     should be paired
```

**Comment by pelikhan** [comment]
Are you missing a pair if the user starts the process in application mode?
```
try to pair
if (connected)
  if (bootloaderMode)
     flash
     pair again
   else
     switch to bootloaderMode
     pair
     flash
     should be paired
```

**Comment by mmoskal** [comment]
right, the flashing will I guess trigger the pairing

**Comment by pelikhan** [comment]
The new flow removes all the various dialog and puts pairing under a single dialog. What about asking the user to enter bootloader mode first?

**Comment by mmoskal** [comment]
I would rather not ask them if we don't have to - depending on what program is flashed they need to hit reset once, twice, or long...

**Pull request closed without merging**
