### PR TITLE
Change jump to toolbox accessibility shortcut

### PR DESCRIPTION
**Pull request by samelhusseini**
Someone pointed out that Ctrl+Left / Right arrows were already used in the monaco editor to jump around the code which is true. I was using that as a shortcut to get into the monaco toolbox. 
I'm changing the shortcut to jump to the toolbox to Ctrl/Cmd + Alt + T instead.

Updated the accessibility documentation to reflect that.

Fixes https://github.com/Microsoft/pxt-microbit/issues/1461

### CODE REVIEW

**Comment by pelikhan** [comment]
This is a good change. I've been annoyed by this in the past.

**Comment by samelhusseini** [comment]
Well.. obviously Ctrl + T is used for creating a new tab in a browser, so any suggestions?

**Comment by samelhusseini** [comment]
Maybe keep using arrows, but add a SHIFT to it?

**Comment by jwunderl** [comment]
Arrow keys and shift is useful for highlighting

**Comment by pelikhan** [comment]
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

**Comment by samelhusseini** [comment]
Shift + arrow (highlights)
Cmd + arrow (Moves)
Cmd + Shift + arrow (up for grabs)

**Comment by pelikhan** [comment]
I live Control+Alt+T free too.

**Comment by samelhusseini** [comment]
I take it back, arrows no good.

**Comment by samelhusseini** [comment]
CtrlCmd + Alt + T it is!

**Pull request merged**
