### PR TITLE
Adding seeed target to the card list

### PR DESCRIPTION
**Pull request by microsoftsam**
screen shot 2017-11-06 at 11 25 38 am

screen shot 2017-11-06 at 11 31 00 am

Tested on: 
- [x] Edge 16
- [x] IE
- [x] Firefox
- [x] Chrome Mac
- [x] Chrome Windows

### CODE REVIEW

**Comment by microsoftsam** [comment]
@Jaqster when you get a moment, waiting for your Approval.

**Comment by Jaqster** [comment]
Approved for Beta.  But not a huge fan of the image - maybe we can switch it out for something that looks a bit more polished for RC.

**Comment by microsoftsam** [comment]
That's the image they supplied, let's give them our feedback and ask for another.

**Comment by Jaqster** [comment]
I don't think we can hold off posting the card any longer.  Let's publish, and aim for a nicer image next time.  Also, what's the logic behind the ordering of cards.  We need to establish a principle early, otherwise we'll piss off partners.  I kind of like the simplicity of in the order that they onboarded...

**Comment by microsoftsam** [comment]
Here's a proposal for a process: 
- Three categories of editors: Non-beta (RC editor), Beta targets, app targets (eg: WW)
- Ordered in the order of which they were onboarded, with non-beta categories first, beta targets next, and then finally app targets. 

This means: 
- microbit, adafruit, minecraft, chibi
- sparkfun, grove zero
- WW

**Comment by microsoftsam** [comment]
Merging for now, will discuss in person later.

**Pull request merged**
