### PR TITLE
Fix decompiling in the gallery

### PR DESCRIPTION
**Pull request by riknoll**

### CODE REVIEW

**Comment by microsoftsam** [comment]
Does this need to go to v0?

**Comment by riknoll** [comment]
This is for the home screen. I don't think it needs to be moved over.

**Comment by microsoftsam** [comment]
Projects dialog in microbit uses the same logic. Perhaps we should move over?

**Comment by microsoftsam** [comment]
I guess it's unlikely you'll end up in this situation as we always create a project on start up / load a project in the microbit.

**Comment by riknoll** [comment]
Eh, it might catch a few uncommon bugs. Doesn't hurt to move it over.

**Comment by microsoftsam** [comment]
Ok moving.

**Pull request merged**
