### PR TITLE
Minecraft -- Fix tutorial load

### PR DESCRIPTION
**Pull request by livcheerful**
Fixes the issue that Andrew was reporting! Gotta make sure things exist before using them :)

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]

**Comment by abchatra** [comment]
Is this a regression? Has this ever worked?

**Comment by livcheerful** [comment]
hmmm it works for you, right?

**Comment by abchatra** [comment]
I am asking from the code side. Is this a new changes we shipped couple of weeks caused this or was this code was always there?

**Comment by livcheerful** [comment]
OH yeah it's from the fix of https://github.com/microsoft/pxt/pull/7876 "fix workspace creeping on the top toolbar" I'm assuming

**Comment by abchatra** [comment]
Sounds good. If you port to /stable we can ship it today.

**Comment by livcheerful** [comment]
oh this is straight into stable I think? The code in master is completely different so we don't need a fix there

**Comment by abchatra** [comment]
Awesome sounds good

**Comment by abchatra** [comment]
@livcheerful  I am forgetting typescript, but **_headers?.offsetHeight_** will resolve to undefined and NaN right instead of 0?

**Comment by livcheerful** [comment]
oh yeah i can put up a fix

**Pull request merged**
