### PR TITLE
add default array.sort behavior for numbers and strings

### PR DESCRIPTION
**Pull request by jwunderl**
fixes https://github.com/microsoft/pxt-microbit/issues/2072
fixes https://github.com/microsoft/pxt-arcade/issues/782

matches javascript at least? Sorting number arrays isn't generally useful in javascript without adding the callback, but at least it will do something.

### CODE REVIEW

**Comment by abchatra** [comment]
Lets wait on this for microbit release. Lets take the fix after the release.

**Comment by pelikhan** [comment]
Moving to dev branch.

**Comment by pelikhan** [comment]
Any chance to add a few tests?

**Comment by jwunderl** [comment]
Is there a place to add tests for these libs files? I'd be happy to, I think there are a decent number of things missing tests in this file that would be good to add tests for

**Comment by riknoll** [comment]
You could copy the compiler test runner and do it there

**Comment by riknoll** [comment]
It runs the simulator in the command line and you can verify the results with console logs

**Comment by abchatra** [comment]
Why are we changing sorting from selection sort? They are typically great for small array. Are there any cases where user has more than 100 elements in an array?

**Comment by jwunderl** [comment]
I mainly changed it on a whim after richard mentioned it at lunch, the largest typical case would be in arcade with sorting sprites / spritelikes for their ordering on the screen.

Was thinking about reverting that for the same reasoning you mentioned earlier today though

**Comment by riknoll** [comment]
If it gives us a performance gain in arcade it might be worth switching for large arrays. Need to verify that it actually makes a difference though.

**Comment by riknoll** [comment]
Relevant piece of code: https://github.com/microsoft/pxt-common-packages/blob/master/libs/game/scene.ts#L134

**Comment by jwunderl** [comment]
I'll cherry pick the heapsort change (https://github.com/microsoft/pxt/pull/5606/commits/9c3bfa8b06a635f67b3285b35e0d68468513aa2f) to another branch and make that a separate PR / test if there's any perf difference - it makes sense to separate a bug fix from a perf change anyway. Probably also make another separate pr for the libs test runner and some initial tests?

**Pull request merged**
