### PR TITLE
experiment: simple reshuffling of buttons

### PR DESCRIPTION
**Pull request by pelikhan**
Made "pair device" primary color and move "download again" as secondary.

See diff without whitespace https://github.com/microsoft/pxt/pull/8117/files?w=1 . What code formatter settings is the team using?

image

### CODE REVIEW

**Comment by Jaqster** [comment]
How hard would it be to put like a big Red arrow overlay to draw attention to where the Download file is?  I feel like that's one of the biggest problems with this dialog... there's a disconnect between what just happened and what it's telling you to do.
Chrome
Edge
Firefox

**Comment by pelikhan** [comment]
It's doable with a bit of CSS trickery. We'll probably want to support this for a subset of browser/versions where we **known** where the files are displayed in the browser shell.

**Comment by pelikhan** [comment]
Unrelated to this change though.

**Review by Jaqster — APPROVED** [review]
Let's try this

**Pull request merged**
