### PR TITLE
Fixing the carousel in RTL languages

### PR DESCRIPTION
**Pull request by riknoll**
Fixes https://github.com/Microsoft/pxt-microbit/issues/1426

Tested in Edge, Firefox, Chrome, and IE

### CODE REVIEW

**Comment by samelhusseini** [comment]
Looks good, we should also test this on touch devices.

**Comment by pelikhan** [comment]
FYI iPhone the carousel is too sensible and capture drag gesture as horizontal. Would be nice to address this too.

**Comment by samelhusseini** [comment]
^^ agreed with Peli, but perhaps in a different change ;)

**Comment by riknoll** [comment]
This PR doesn't really change how touch is handled at all, just reverses the direction in RTL

**Pull request merged**
