### PR TITLE
Add palette picker/editor experiment

### PR DESCRIPTION
**Pull request by riknoll**
palette-picker

Adds an experiment for use in pxt-arcade that lets you change your project's color palette! 

Obviously this has gone through zero design iterations, so don't expect it to turn into anything other than an experiment anytime soon. Most of the palettes came from [lospec.com](https://lospec.com/palette-list) via @jwunderl's pxt-color extension.

I went through and reordered the colors so that they are somewhat close to our default palette. This makes it so that the gallery sprites are still somewhat usable.

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]

**Comment by jwunderl** [comment]
(in future, we could add support for importing using e.g. the .hex format output of lospec
image
or gimp palette format 
image
but that's more on the 'possibly nice to have' side~)

**Comment by LucasMayhew** [comment]
So I can no longer do this ?

**Comment by LucasMayhew** [comment]
Why???

**Comment by riknoll** [comment]
@LucasMayhew this hasn't been pushed to beta yet. in the meantime, you can still override the palette in the usual way

**Comment by LucasMayhew** [comment]
Okay

**Comment by LucasMayhew** [comment]
any idea when it will be pushed like in the next few weeks or so

**Comment by LucasMayhew** [comment]
Also it is soo hard to change the palette the old way

**Comment by LucasMayhew** [comment]
I am sooo Hyped for this thing

**Comment by riknoll** [comment]
@LucasMayhew this is now in beta. you can turn it on like this:

1. Click the gearwheel menu
2. Click "About"
3. Click "experiments"
4. Click "Change Color Palette"
5. Click "Go back" and wait for the page to reload
6. You should now see "Project Settings" in the gearwheel menu when you have a project open

**Comment by LucasMayhew** [comment]
YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES

**Pull request merged**
