### PR TITLE
move variants after boards

### PR DESCRIPTION
**Pull request by pelikhan**
Reorder download dialog to put physical boards first.
image

### CODE REVIEW

**Comment by abchatra** [comment]
Can we move Pi0 to the last?

**Comment by Jaqster** [comment]
Yes, much better.  Let's put the "Build it yourself Adafruit M4" at the end though.  Also, can we remove the Pi0 custom one?  That's only for the Arcade cabinet, right?

**Comment by pelikhan** [comment]
Pi0 is the variant for Adafruit Joybonnet or any Raspberry Pi 0 arcade like the PiCade.

**Comment by mmoskal** [comment]
`Pi0` is the same as `Adafruit Joy Bonnet`, the same way as `F401` is the same as `Brainpad`. I think we should keep all the ones that are "bootloader" screenshots for consistency.

**Pull request merged**
