### PR TITLE
updated contact.md

### PR DESCRIPTION
**Pull request by DoctaCloak**
# Update to `I'm a Developer!` Section

image

- Added a link to the new Discord channel, since Gitter is not being used.  This way newcomers won't have to join Gitter to read the message that we have moved to Discord.

### CODE REVIEW

**Comment by riknoll** [comment]
@DoctaCloak looks like you added your edits to the end of the file instead of updating the existing text

**Comment by DoctaCloak** [comment]
Made changes.  @riknoll  😃

**Comment by riknoll** [comment]
Could you switch the link to https://aka.ms/makecodecommunity ? Otherwise looks good!

**Comment by DoctaCloak** [comment]
Done @riknoll  🙂 By the way, how do you generate a link like aka.ms?

**Comment by riknoll** [comment]
It's Microsoft's internal URL shortening service. Sorta like Google's `goo.gl`

**Pull request merged**
