### PR TITLE
Add null+type check on method invocation

### PR DESCRIPTION
**Pull request by mmoskal**

### CODE REVIEW

**Comment by pelikhan** [comment]
LGTM. Errors messages are less confusing with this but still very well hidden. @abchatra  your call.

**Comment by riknoll** [comment]
@abchatra I think we should take this change for beta. You get these errors with sprites all the time

**Comment by abchatra** [comment]
lets take it. Merge to stable5.8

**Comment by pelikhan** [comment]
Who does the integration?

**Comment by abchatra** [comment]
I will do it.

**Pull request merged**
