### PR TITLE
[Accessibility] Fixed the color contrast issue in the documentation

### PR DESCRIPTION
**Pull request by veler**
Fixed an issue where the color contrast of the green text in the documentation was not correct.

Related issue : [https://github.com/Microsoft/pxt/issues/2528](https://github.com/Microsoft/pxt/issues/2528)
Related PR : [https://github.com/Microsoft/pxt-microbit/pull/536](https://github.com/Microsoft/pxt-microbit/pull/536), [https://github.com/Microsoft/pxt-sparkfun/pull/47](https://github.com/Microsoft/pxt-sparkfun/pull/47), [https://github.com/Microsoft/pxt-minecraft/pull/322](https://github.com/Microsoft/pxt-minecraft/pull/322), [https://github.com/Microsoft/pxt-adafruit/pull/323](https://github.com/Microsoft/pxt-adafruit/pull/323), [https://github.com/Microsoft/pxt-chibitronics/pull/68](https://github.com/Microsoft/pxt-chibitronics/pull/68)

For some reason, this issue was fixed by the past but has been reverted at a moment. I think it's when we moved some changes to PXT instead of PXT-microbit.

untitled

### CODE REVIEW

**Comment by microsoftsam** [comment]
Do you need to also update _theme/theme.config ?

**Comment by veler** [comment]
Yes, the change was not applied otherwise, even if we were changing the theme.config  in the targets.

**Comment by microsoftsam** [comment]
I mean _theme inside pxt.

**Comment by microsoftsam** [comment]
Merge into master change?

**Comment by veler** [comment]
Done

**Pull request merged**
