### PR TITLE
display version info when running in electron

### PR DESCRIPTION
**Pull request by pelikhan**
I find it frustrating that i dont' know if the elecron app is updating or not. Add some info about online version availability in electron.
* not online -> please connect to internet to update
* online, updated -> you're up to date
* online, outdated, an update is avilable
image

### CODE REVIEW

**Comment by pelikhan** [comment]
@abchatra this is a simple hint like Chrome about the current version.

**Comment by abchatra** [comment]
I don't understand the change. How do you know the update is available? Just based on the live version? We may not have released the latest one yet. It should say update available only if there a latest electron version available.

**Comment by pelikhan** [comment]
My assumption (which may be wrong) is that ``targetConfigAsync()`` pulls the live version of ``targetconfig.json``; then we can compare the version in ``electronManifest.latest`` to the current version. Since the electron layer is already doing that work, it could be added to the ``onStatusUpdate`` event too.

**Comment by abchatra** [comment]
I think you are right and it looks good. Ideally we can link to download page to update too (assuming automatic update is failing for some reason)

**Comment by pelikhan** [comment]
Is there a default url scheme for the download page? I can add a link.

**Comment by abchatra** [comment]
I guess we don't have latest URL probably we should add to the backend api

We have this in the download page. It is annoying to edit it every time. 

```
            window.open("https://makecode.com/api/release/microbit/v1.2.13/win64");
            tickEvent("offlineapp.download", { "target": "microbit", "platform": "win64" });
```

But you could make the url from the electron.manifest version
https://makecode.com/api/release/microbit/[[electronManifest.latest]]/win64

**Comment by pelikhan** [comment]
Just add JavaScript that downloads the target config and generate the url.

________________________________

**Pull request merged**
