### PR TITLE
Add support for math functions and constants

### PR DESCRIPTION
**Pull request by riknoll**
This PR adds a math function block. My criteria for which functions were included was mostly about which ones I have ever used in my life, and the list I came up with was:

1. `Math.sin(0)`
2. `Math.cos(1)`
3. `Math.tan(2)`
4.  `Math.sqrt(3)`
5.  `Math.ceil(4)`
6. `Math.floor(5)`
7. `Math.atan2(6, 7)`

And here are the ones that were cut:

1. `Math.asin(0)`
2. `Math.acos(1)`
3. `Math.atan(2)`
4. `Math.log(3)`
5. `Math.exp(4)`
6. `Math.trunc(5)`
6. `Math.round(6)`
7. `Math.imul(7, 8)`
7. `Math.idiv(9, 10)`

In addition to functions, I have also added support for constants on namespaces. It works exactly like enum blocks work; you add a dummy shim function (with the comment attribute `constantsShim`) and then annotate the constants you want in the dropdown with `blockIdentity="qName"`. I don't do any type checking.

@ganicke I filled in some placeholders for the tooltip text so take a look!

### CODE REVIEW

**Comment by riknoll** [comment]
It looks like this (except I removed a few functions from the list, see above).
math_functions

**Comment by pelikhan** [comment]
Why not add them all?

________________________________

**Comment by riknoll** [comment]
@pelikhan take a look at the GIF, the dropdown is so long that it scrolls.

**Comment by pelikhan** [comment]
Can we simply use a grid? All good here names are rather short.

________________________________

**Comment by pelikhan** [comment]
Let ‘s try to be 1-to-1 with JS.

________________________________

**Comment by riknoll** [comment]
We aren't 1-1 with JS. The functions we support are a subset of the math functions anyway, we are missing a lot of them

**Comment by pelikhan** [comment]
Can I get log/exp? Does not make sense to expose E Without those.

________________________________

**Comment by riknoll** [comment]
I don't care strongly about what we include, I just want it to look nice and have the useful functions at the top. Never been a fan of grid pickers with text. @samelhusseini any ideas?

**Comment by samelhusseini** [comment]
Most math functions have symbols so a grid of images might work well here

**Comment by riknoll** [comment]
Works for me. If we wanted, we could split up the "math-y" ones from the JS ones. That is, move `ceil`, `floor`, `round`, and `trunc` to a different block since they do not have symbols.

**Comment by pelikhan** [comment]
It is just going to be a long list I am afraid.
________________________________

**Comment by pelikhan** [comment]
We could split the number manipulation from the scientific operands (trig / exp / log etc..)

**Comment by pelikhan** [comment]
Let's get those in and add more later.

**Pull request merged**
