### PR TITLE
moving import/new/save as buttons

### PR DESCRIPTION
**Pull request by pelikhan**
A small reorg of the projects dialog until cleanup. Note that save and rename should eventually move away to the new toolbar.

image

### CODE REVIEW

**Comment by abchatra** [comment]
Looks good me. But why is import next to search bar?

**Comment by pelikhan** [comment]
Import is related to "opening a script". The above buttons are related to the current project.

Save, rename should move out to bottom toolbar soon.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by microsoftsam** [comment]
Looks good. Minor comment, could make the import button attached to the search box. (similar to the search icon at the end)

**Comment by pelikhan** [comment]
Merged in https://github.com/Microsoft/pxt/pull/1052

**Pull request closed without merging**
