### PR TITLE
Rename item variable to "my variable"

### LINKED ISSUE #1539: Change default variable name
From "item" to "myvariable".  This has been confusing for some users, so let's make the default variable name super clear.  

Longer term, we should think through a better workflow for creating, assigning, and using variables.  Right now, it's not intuitive.

### PR DESCRIPTION
**Pull request by microsoftsam**
Fixes #1539 

screen shot 2017-03-06 at 6 50 30 am

### CODE REVIEW

**Comment by pelikhan** [comment]
Could we not have a default variable?

**Comment by microsoftsam** [comment]
Not sure what would happen to the OO apis @riknoll ?

**Comment by riknoll** [comment]
I actually have no idea. Blockly might just add the variable if it doesn't already exist.

**Comment by microsoftsam** [comment]
Okay will try.

________________________________

**Comment by rachel-fenichel** [comment]
Hey there--I manage variables for Blockly.  Feel free to ping me with questions.

**Comment by pelikhan** [comment]
@abchatra  We should either take this or close it.

**Comment by abchatra** [comment]
I don't know if the 'myvariable' is a good name, 'item' is definitely not. May be a topic for design discussion.

**Comment by pelikhan** [comment]
Renaming it would be a UI breaking change.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
Yes, only for microbit

**Comment by pelikhan** [comment]
Maybe it should be called "that" or "stuff"

**Comment by Jaqster** [comment]
We need a default variable.  My vote is for "myvariable", or "myvar" if that's too long.  It's the clearest indication of what it is.  Imagine a teacher using MakeCode to teach students about variables in computer science.  "that" or "stuff" would not be a good name in this scenario.

**Comment by riknoll** [comment]
Scratch uses "thing" to refer to items in their lists.

**Comment by pelikhan** [comment]
I like "thing"

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by microsoftsam** [comment]
@Jaqster @pelikhan @abchatra are we retiring this?

**Comment by abchatra** [comment]
I am indifferent. You folks decide.

**Comment by Jaqster** [comment]
I'd like to leave this open - we need to be consistent with our default naming.  I'd like to suggest: "myvariable", "myindex", "myarray", "myfunction".  Makes it much clearer/standard than random "item", "index", "list", "dosomething".  And will work across targets.

**Comment by pelikhan** [comment]
How about no default? Variable list should be empty to start from.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
Reopen when we are ready to tackle this.

**Pull request closed without merging**
