### PR TITLE
Add controls_advanced_for block

### PR DESCRIPTION
**Pull request by sae220**
https://github.com/microsoft/pxt/pull/10025

### CODE REVIEW

**Comment by sae220** [comment]
@riknoll 
Could you review this?

**Comment by THEb0nny** [comment]
Hmm, why is no one reviewing this change?

**Comment by THEb0nny** [comment]
@sae220 Can you show what this looks like? Screenshot.

**Comment by THEb0nny** [comment]
@sae220 why did you close it?

**Comment by sae220** [comment]
@THEb0nny 
Sorry, this is unintentional close.
When I worked in another PR, I forgot to checkout branch and pushed to main branch. So I deleted my fork repository.

I'll recreate the PR and show screenshots in few days.

**Comment by THEb0nny** [comment]
@sae220 have you given up on this? I would like to see this change.

**Pull request closed without merging**
