### PR TITLE
Translate into french and korean this project

### PR DESCRIPTION
**Pull request by hulyaa**
I want to Translate into french and korean your project for my master and new project with utopiam please

### CODE REVIEW

**Comment by hulyaa** [comment]
I want to Translate into french and korean your project for my master and new project with utopiam please

**Comment by hulyaa** [comment]
sorry I signed.When I get a reply please

**Comment by pelikhan** [comment]
Information about translations at https://makecode.com/translate. Thank you!

**Comment by hulyaa** [comment]
thank you very much for your answer

**Pull request closed without merging**
