### PR TITLE
More robust cloud sync error reporting (#7997)

### PR DESCRIPTION
**Pull request by darzu**
* Adds more identity tick events
* more robust cloud sync error handling
* wrap in Error()

### CODE REVIEW

**Comment by darzu** [comment]
Force merging so hopefully it makes it in the release testing. @abchatra

**Comment by abchatra** [comment]
Give me some time. I am going to take a look

**Comment by abchatra** [comment]
Typically, ticks are for user action and it is ok to use them for debug purpose if the ticks are limited.

These are debug ticks. What is the number of these ticks per session?

**Comment by darzu** [comment]
For normal sessions, we currently expect about ~2 syncs and ~15 saves, each of which will generate on average 1-2 of these new ticks. So about 15-30ish ticks per session.

Do we have a system for debug ticks? They are a useful pattern for debugging occasional and hard to repro issues.

**Comment by abchatra** [comment]
30ticks is ok per session. If it is like 500 I would be concerned. We use log to console (using debug flag) and ask folks to send the logs

**Comment by abchatra** [comment]
I am going to merge this. But keep an eye on the number of these ticks per session. If it is too much lets dial down.

**Review by abchatra — APPROVED** [review]

**Comment by darzu** [comment]
Log to console with debug flag and manual sending error reports is great for some scenarios but really not good if you're trying to figure out how many people are hitting certain error cases or investigating a rare issue after it has already happened.

We have a system for reporting and tracking exception telemetry already, right? Does this use the normal app insights channel or something else? Can we extend that for debug ticks?

**Comment by abchatra** [comment]
You can log failure scenario. But you are also logging success scenario. 

We already send all exceptions to application insights.

**Comment by darzu** [comment]
Okay, I'll remove some/all of the success scenario logging as we expand identity to many new users. The error cases are the most important. The exceptions are only occasionally useful since they don't capture all the context needed.

**Pull request merged**
