### PR TITLE
Merge branch 'stable7.1'

### PR DESCRIPTION
**Pull request by eanders-MS**
Merging stable7.1 to master.

### CODE REVIEW

**Comment by eanders-MS** [comment]
I'll keep this open until we're done working in stable7.1.

**Comment by abchatra** [comment]
Merge to master & bump?

**Comment by eanders-MS** [comment]
Sure, will do that shortly.

**Comment by eanders-MS** [comment]
PR needs sign off.

**Review by abchatra — APPROVED** [review]

**Review by abchatra — APPROVED** [review]

**Pull request merged**
