### PR TITLE
cut sim volume a bit

### PR DESCRIPTION
**Pull request by jwunderl**
Make it less startling: can compare https://arcade.makecode.com/79623-16989-79723-53384 and https://arcade.makecode.com/app/ec5c0258e39de822efe8382124500bd128aff490-58aedfd1f9#pub:79623-16989-79723-53384

### CODE REVIEW

**Comment by Jaqster** [comment]
The wawawa is especially obnoxious...  other sounds seem fine at this level, but I almost want even lower volume...

**Comment by jwunderl** [comment]
I already started special casing the wawawa with the square noise, could lower it from .7 to .5?

**Comment by Jaqster** [comment]
Yeah, let's try that

**Comment by jwunderl** [comment]
Okay here it is with that: https://arcade.makecode.com/app/f3a549e77b25e3a011e4af1079c3ff3d1aa11d5e-9378dbdaee#pub:79623-16989-79723-53384

**Pull request merged**
