### PR TITLE
[Accessibility] Fixed not descriptive enough link in the blog

### PR DESCRIPTION
**Pull request by veler**
Related issue : [https://github.com/Microsoft/pxt/issues/2647](https://github.com/Microsoft/pxt/issues/2647)

This change affect only the blog of PXT. Because of that, I did the changes on a branch based directly on master.

### CODE REVIEW

**Comment by microsoftsam** [comment]
@ganicke please review.

**Comment by ganicke** [comment]
Pushed a push back on the 'read more'. If you hate it, then nuke my last commit. Most blogs don't even include a 'Read more', just '...' or '.!?' with just the title linking to the article.

**Comment by veler** [comment]
I totally agree that "Read more" must be fine. It's just not the opinion of the accessibility team on the following issue : [https://github.com/Microsoft/pxt/issues/2647](https://github.com/Microsoft/pxt/issues/2647)

If it was me I would keep "Read more".

**Comment by ganicke** [comment]
Hmm, do we obey the accessibility team or do what's 'cool'. Anyone who knows they are on a Blog page should know that the stuff listed on the page are article links, no? Seem obvious, even with a screen reader that says "read more" means -> goto article.

**Comment by veler** [comment]
Seem obvious to me too. What do you think about @sam and @abchatra . We already did some similar changes in the documentation and merged it.

**Comment by abchatra** [comment]
Seems obvious to me. @veler can you ping the accessibility team and tell them it is descriptive enough in the context? In my opinion we need to push back on this

**Pull request merged**
