### PR TITLE
AP CSP course landing page

### LINKED ISSUE #7830: AP CS Principles landing page
Hi Galen,
Can you post this landing page for the new curriculum that's coming out?
Thinking to put it here: http://makecode.com/csp 
Once the curriculum materials are done, we can add the link for the downloads.
Content files for the landing page are here: https://microsoft-my.sharepoint.com/:f:/p/jacqchen/Ep-LqBN5cKBLiEE8b92dbf4BnY0aNtbRGb33nslxbYxC3w?e=rK8OzW
Let me know if you have any questions.
Thanks!
Jacqueline

### PR DESCRIPTION
**Pull request by ganicke**
Import, format, and edit CSP course page text and images.

Comments:

* The course page example images are set in three column tables.
* There is no link or down links to course material (I assume that's coming later).
* Put a link for this page in the site SUMMARY for this page?

Closes #7830

### CODE REVIEW

**Review by Jaqster — APPROVED** [review]
Love it!  Looks great Galen!  Go ahead and merge (when Travis is back up).  The curriculum materials aren't quite done yet.  When they are (should be in a week or so) we can insert the download link.

**Comment by Jaqster** [comment]
Can we merge this now?

**Comment by ganicke** [comment]
@abchatra - Can you punch this in for @Jaqster and I. Travis will never finish for this.

**Review by jwunderl — APPROVED** [review]

**Comment by ganicke** [comment]
Thanks @jwunderl! :relieved:

**Comment by pelikhan** [comment]
I look at the https://makecode.com/csp page and i can't find the link to the content.

**Comment by ganicke** [comment]
@pelikhan - https://github.com/microsoft/pxt/pull/7831#pullrequestreview-576541724

**Comment by pelikhan** [comment]
Oh. I see. Definitely need a SUMMARY here too when it is done.

**Comment by ganicke** [comment]
Right. Not sure what the reason for putting it up early was. Probably an external referrer needed it published to satisfy some linking.

**Comment by Jaqster** [comment]
Yup, we needed it for the TEALS Pilot program.  The materials aren't quite ready to post yet though.  Peli, what kind of Summary should we add for this page?

**Comment by pelikhan** [comment]
I was just trying to look at the actual content. I’ll wait I guess 😊

**Comment by ganicke** [comment]
He means put in an entry or or add a SUMMARY.md (the veritable TOC) for it.

**Pull request merged**
