### PR TITLE
Better drum sounds and add support for bass clef to drums

### PR DESCRIPTION
**Pull request by riknoll**
This improves the array of drum sounds that are available.

If you want to hear them, here's an arcade project that has 'em all:

https://arcade.makecode.com/beta#pub:52073-79957-62825-57855

Also it makes it so that you can add drum sounds to the bass clef, so 24 sounds are now available!

### CODE REVIEW

**Comment by riknoll** [comment]
oh also it changes the lemon sound so that it's no longer the same as the computer sound.

**Review by jwunderl — APPROVED** [review]
I'm just believing in you on the `pxtlib/music.ts` side but the rest LGTM

**Review by eanders-ms — APPROVED** [review]
We need another tech talk on this :)

**Comment by riknoll** [comment]
@eanders-ms i'm always happy to talk about sound synthesis 😄

**Pull request merged**
