### PR TITLE
Cherrypick skillmap & asset editor fixes

### PR DESCRIPTION
**Pull request by abchatra**
Display unlocked rewards out of total reward count in skill map (#7992)
Adjust the asset editor sidebar in asset editor-tutorials (#7999) 
Don't allow reserved words in kinds (#8004)
Only match recognized snippets when parsing tutorial metadata (#7995)
Add customts snippet type for loading hidden ts into tutorials (#7994)

### CODE REVIEW

**Comment by riknoll** [comment]
Should also take https://github.com/microsoft/pxt/pull/7998

Sorry, forgot to merge it yesterday

**Review by shakao — APPROVED** [review]

**Comment by abchatra** [comment]
Can you do a the PR to stable?

**Comment by abchatra** [comment]
Hmm #7988 is a big change. Should we wait to be stable in /beta before taking it?

**Comment by riknoll** [comment]
We can do that, but it fixes some major bugs around undo/redo. I think we should have a plan for releasing it next week if not this week.

**Comment by abchatra** [comment]
Up to you. If you think changes are not risky, we can take now otherwise we can do a point release next week. What is your preference?

**Comment by riknoll** [comment]
The changes are risky.

**Comment by abchatra** [comment]
Lets wait for a week or so and do another point fix then.

**Pull request merged**
