### PR TITLE
Add start value in "for" loop

### PR DESCRIPTION
**Pull request by sae220**
https://github.com/microsoft/pxt/issues/8970
https://github.com/microsoft/pxt-microbit/issues/3837

### CODE REVIEW

**Comment by THEb0nny** [comment]
We need such an update!

**Comment by sae220** [comment]
@riknoll 
Could you review this if you have time?

**Comment by riknoll** [comment]
@sae220 I don't think we can merge this PR. it would break too many existing screenshots and documentation that uses the old for-loop. we've done a lot of iterating over the for-loop internally over the years and we've always run into walls with feedback from either partners or teachers when trying to update it.

**Comment by riknoll** [comment]
@sae220 that might be doable, but we'd probably want to put it behind an experiment flag to start. do you know how to add something to the experiments dialog?

**Comment by THEb0nny** [comment]
@sae220 change does not support setting the step?

**Comment by sae220** [comment]
@riknoll 
I don't know but I'll refer to https://github.com/microsoft/pxt/pull/6809. Is it OK?

**Comment by sae220** [comment]
@THEb0nny 
This pull request doesn't support the step but I'll make a new pull request support it.

**Pull request closed without merging**
