### PR TITLE
Fix toggle language behavior, some CSS updates

### PR DESCRIPTION
**Pull request by shakao**
Fixes https://github.com/microsoft/pxt-arcade/issues/2505
Fixes https://github.com/microsoft/pxt-arcade/issues/2499
CSS pass for https://github.com/microsoft/pxt-arcade/issues/2478

image

(Darker one is hover behavior)

### CODE REVIEW

**Comment by shakao** [comment]
@soniakandah would love any feedback you have for modal design!

**Review by jwunderl — APPROVED** [review]
Oh wow the teal looks fantastic here.

I was just about to file one other bug if you could check if it's fixed here - on pxt/master in microbit (e.g. https://makecode.microbit.org/v3.1.5) there's an issue when javascript is selected:

image

(maybe sometime we should revisit the language toggle / specifically make the highlighting easier to manage)

**Comment by soniakandah** [comment]
@shakao I think this looks great!

**Comment by shakao** [comment]
@jwunderl i'll take a look! yeah tbh i would love to ditch and rewrite the toggle styles completely, the current system is not very extensible or configurable... it might not be too hard, i think we could do it just by scrapping all current CSS and using classes based on the toggle position (first/second/etc) instead of specific editors

**Review by livcheerful — APPROVED** [review]

**Comment by shakao** [comment]
@jwunderl microbit toggle isn't fixed by this change, feel free to file it--i'm gonna take a quick look at the toggle and see how much work i'd be to tidy up the css!

**Comment by abchatra** [comment]
This looks great. Thank you @shakao

**Pull request merged**
