### PR TITLE
added UIntYYYArray.some polyfills

### PR DESCRIPTION
**Pull request by pelikhan**

### CODE REVIEW

**Comment by abchatra** [comment]
There is another polyfill in worker, update that too please.

**Comment by pelikhan** [comment]
It is not used in the worker. Fixing duplication of polyfills should be fixed but not here.

**Comment by abchatra** [comment]
Lets add for both as we will hit that bug some other time.

**Comment by pelikhan** [comment]
Polyfills are not consistent at all between worker and sim. It's not just that one.

**Comment by pelikhan** [comment]
Added a few polyfills but it's by no means complete.

**Pull request merged**
