### PR TITLE
un-lexically nest function

### PR DESCRIPTION
**Pull request by jwunderl**
Lexically nested functions are not allowed in strict mode in old safari (I'm personally very surprised they're allowed in any strict modes)

should fix https://github.com/microsoft/pxt-microbit/issues/2237, although I haven't yet tested this patch on the current microbit build (not sure which branches to use) - but this fixes it at the point it was first broken, and I don't think this is a common paradigm

### CODE REVIEW

**Comment by jwunderl** [comment]
../node_modules/@types/request/index.d.ts(21,27): error TS7016: Could not find a declaration file for module 'form-data'. '/home/travis/build/microsoft/pxt/node_modules/form-data/lib/form_data.js' implicitly has an 'any' type.
  Try `npm install @types/form-data` if it exists or add a new declaration (.d.ts) file containing `declare module 'form-data';`
jake aborted.

**Comment by pelikhan** [comment]
@jwunderl this fix needs to be integrated into stable6.9

**Comment by jwunderl** [comment]
I thought it was 5.15, got the pr cherry picking to that branch here https://github.com/microsoft/pxt/pull/5759? Either way, I will need to work with @abchatra tomorrow / as soon as we can to get this to the live site

**Comment by pelikhan** [comment]
It is the version referenced in package.json (https://github.com/microsoft/pxt-microbit/blob/master/package.json#L49) so yes 5.15

**Pull request merged**
