### PR TITLE
change assetjson encoding to prevent translation errors

### PR DESCRIPTION
**Pull request by riknoll**
This is a draft pr that hopes to fix the "could not upload translation because line is too long" error that keeps cropping up. Right now we include assets in a tutorial by just pasting a JSON blob into the markdown that contains the entire source; this can get very long for tutorials with background images. To get the aforementioned JSON blob, you add `?saveAsTemplate=1` to the url in the editor and click the save button to download the project as a JSON file.

This changes the format of the file downloaded by `?saveAsTemplate=1` to instead be a base64 encoded LZMA compressed project file that is split over several lines. In other words, instead of this:

```````
```assetjson
{
  "assets.json": "",
  ...
}
```
````````

you now paste this:

```````
```assetjson
XQAAgAAuPQEAAAAAAAA9goAXHC4MqgeNHgoIMpsTCTurzyZquKQOb1TCv3qwmPyG+YAK6z7nP4WLOdVfWC6WyAOfkE0nQj0EIuV/
hdiNSF6jWtqSyE3s06pVSwMxtMtTPcAv7TGwuJf8tJo2/ZxOPMNdkK8Ge/58mBDqVB/hKNlFR9Qx1UYExX/0HbOtqhswFeD8Cts2
fBuLRUfSNCj76wgq6qCe4T/PKl1/DtuSi4TnK47BzLy14sZaWiSllK0XbIplxc0nmXn35yGJbLMylUTDBA82Xkjy2LjWfynOE5jU
dSWOKIW2TJL+9gBgE2KLLr6K9hG0AcgJV2DdiYlxeEHoYzV810dKTyd4SnMLW9AysiiCVaycMA4vG9C7U518g/kS2NC5KAr0zcb5
DwinRG3CvfLIR8Y9Zd9HWHxefUtRGAN2R4fP/EGmuzEXXqZ1aaILQzYIPymP+CMcnpSM1zd9f3MPXBxt2v08V25KZLPD9TJXoydZ
3OZY/XAg+ag3TtCzx+ZiAhaEZ4TqFWPd+nHt0W0sOJUL0QW1/WpHCC4DlZQd4c/VnShDjQzX5px7bgKPWNCoLCu748JaPnex1OrB
o1HNOkgasqNlzivwAQc6/LRvAjqc1XMhPJEp/Pg20thbUYXkPM3Ki03JqaylEpfRuBPTgV5F5Yq4pGhKvuebOyaNBTJCoQKKg2ez
WoyM4RhS3DFU1dLPxHP/IprXzCVJRezH9NlmFj9BxHXx87j0Njp55idKMi9v7nTwR4wiieMzJQGqZ+ubJsfypL8+8AfUFRW/9nZc
tG9t2SXU7d+ekyBHCuNDPFGegwXjTU2ih/ctpzit7MF4C9y+ixtGwYsGD1y0oLxKcpFrQhcl7Vi/kjFDt2XaHFZb0cFcnhm3vdXk
D4A+fKZca7TOgNAD6QYvdTMLWz0RIS8SizloOSp5LHcZurIWomx8vlcFWBBGnMPSMtB6iNHx1lovbjZnPvJ9cYS1A5v0m7MOut7F
3jyJss8nQcIM89QPpMZg/7RxGV/kqhg2QsT1Sw9JKU24A6Bxr/a1pRCqCjCNAV04X/XcRICStnBnJCTy0xGd6BwClIQmBriSnNPM
UHYraSoreEzh7zpgBzCSe/Ic9bg5fSKA4t5EnXnlWPqkWAW5DyEcz1aAa92Ed/Z9YFnm5L3giPBMA5zMvbCi9Wl1q0cssts92JU3
VscPUf4PHR1F97FrnpW4chL9AAb7J5DrRffQxZjX70yzA/GgEPWmdW870FSuhBV/OJwImRcG3gZkp+KZE6gPgFynZrgTwjwVb/Ku
KfbHttPj7IoWSk1+qrY4XxUYbLqsjDOPUA5kQPc/NiaaInAkSVebiXFsMrUIPFKAgvPtvbPTzJQBBmdcNL02/bAR8irNMDalJtp4
lfMazw4xtotvt+mmSUkQDVAU49zIwoT8kUpIPLSDB1allcU8bgk8iOeZrkDDy9jxnKFH15ERgZ57J92HUhIX1frlMz/4OkJcjy8b
Y9yrqLvH7ibNuzeJ6JMqN16FekHoRW9LvlGJoLpSJfo2BQZsQFuHnzeqODzNQi4uqanGbmrF4/ISw/9I5g8h0/W9EmSOVlebXeIK
/H9aut3CENuwm8qyJUE0UQL9/SGGX7dtfsUucXf2R+lHepGsIdLxL24d8kmy71f3DR0aoZyYp6UskR1Oy1QmuCjn1dzf1WZqyseQ
twuU1mTYXgRt6QyuaKo6V90kp+A5NXKZhJboHWqV1E/vEpmMU/4fWxkG7hOQrg9lkRzC4ztiSbybf52n6mLgaVAWf2ufTNJoNRN+
7WNq1bWLatEZsin2m5NTQSL1EtD+ZZRqDA849irHDHzdq4VDONF/SHVG59oyMsaZwqk6HEBzT/LUKt1irwOCqLbK/US/z3YTmOPM
u4wRhWjiH6R/e5a8TvuDWuK2kA5gahIjdKOj0S17r2tbeovKUzdpKktxaBWHDNvc5sPXfrs4z8dPw7bXx71KwL7asv0Kk1OicrER
qX8PrPKNNj2waNRk08iN3cVVk6jkamNI2Yyxi4fkNBGAqEubDUSvnK/2hfIQDaEk7YE55RQ7WxS3k3NBABbRVlj3GqaJH8Or0oTV
jCfJ0nrpQfvITbTXoU2nArufyU5jO0CcFcgqvwtBc5yRyQ15Bktk2NGO26Ra+oOcnCcCmKrBC5Z8qzec94Z/Ci94xKcdMx6tNLmi
ESk8Hn/HayWAyddqJQUU1hMKek1ZrPAo5UgeNvztpoXcOPx/HohFVuOFufwknGTbDuo+DzsuSMzglEyHfq1q18dmvJq2+44+KU+C
8uzlJTPPWf7Ax+r1KnyZc3RxSq+vP2iR/70lS7PDd85a0qzu3ARn6zMSRy4cQgpBk+v1CAdMjPDndbqSuZnMWbJNeRXrrozbsS52
LkB+arxHfYDG32TOBG30Ji+TLXCjTlWY3/SGzsV7jygcQ86IFP1Mc0udav9pRaSxkI89GP70kAKl/Ht6kFK9CAw2/t/Zn9xILS02
9rABKa1xclQ0U6zRJTEG1VwhWSBiJbCQ0dg9mX2Wa+ebwFWjP9m3Ro6ZlsbfjM15t8kkMEZ5B/jwgojkpRxI6U5iV4IjXwGVbnI5
s45whMG/tfZZVKoGnOUS1Kef5wISLQsCr3rTZ/Xqg/hzWgZrDQqlCdJMkhDvIjb4rxx721qWAQHgypwft5JBNKrQYx9PsXWGdkeH
7LJmQvm4Ng4m8r1OvtULPKfXoFj6U51eg8n6p0x0IP+5bCiMn6UC4xOr/wSEjljM+RQUwgF8Gn2JeBFwH8L5TBcJMK8pYDeR9eU1
dafmqtG4zSpxYlYSQ1BbSor6wjXOItQSw1apDDa88yveNNmZSgLhJ6zksdiBB0i51pkiS0kSh6o7hRXv+51M1duECbjTbujMTdS4
i/ptOBmglZkoRksizfY0BbUJDDwnRzis68Wh4De5nkHrz2/LMTKEF5erJMHXpvWPLEjM7pBbZunr4wzXnW+3q7k1/jEAx//rCXTz
/j4pPEmPAzf4aiNcEOl5nHS2WPD3wxPdBJ7pfBgwCT0ZETiqa+NNtdUULSTBk+oipd4+7MmzxQwy9WOMK2zETUBV1KCZp1ZyNIiO
EZdivuZt4yW9ZXNaH62sNX7Q7+eaxStXNPfFytfqOXqEjNLpZ93w06rF1fNqANj4wBw61q2vTNYedeqcdeYsaUZLgKGeHtEwsixj
VCwXqN2dOhNXht2etL3RYPEpq/gR2ocDpnDWQtB3t29uneDMVcAzDjoCi/0IhOp1ZaCA3fB3/Roj3QVTwNPqcvEoBlbfLxTGV575
0NSgTXzm4jXFKyjNypRCZtoh3D77LczxXQThosgmnIl2a8DKSaYUVEXq4jbTspi6z+5Xf0NMDk8n9Ntl3ut0LRNHY68a5zExyGyf
8y2GQIxV8BI4tKZ6f0l4dVbqjr6s2Klsy/8hKTm6VRQMbKH+vsBcgZuvr6gXggUHpi1O6MrmEoQJUUP375TNAGHkC5aArLKmxRGh
p72QlX+KtbC7pRMjgy7t5EcliNqzq9h6PUiIDOXrLfCtUhmT+2EfHKNwimbSxJ2IKDdRYtNioCevF9NN5oB+e09fHOSKolS9IsOf
xumgWzEZadoKO5qh+p7XtodcVt/YW6sbmjLOpar9h1di/n1oShUjJjjekBP4EtvMb9ZZAeTM88mS4ZfnKgIZneYbqUaLNEZlWqFk
3Gm4lbKztaaleDTPetN6RfghRWhJHmf/88kk6ftkC0TIwxm2fAyGDtRr7vzNRUX2znyVuwKM7IEI7H9MM7aDhwMNvCD3dfU9/fI3
QvueOAKkKyEc7om3rDjtk8t03ZSxP3CjXuYvkrtAKqxvQknwebNoSYE9oflgJXLLxHNlp9ndwr1FJYfYAbYz48zV7gCmh3XpdFg+
1qwrRYC2w7aUqVlFefSGXkBvuneAgPdIfgSFxolRPa4t+o9fRaTuwlJeGxrx73vOvvYA7cLZFVBF8T+2W/8lgTEQq9k9hQUmNA2c
aF9Hg9uPYwYztisTbOrkdPNsq2QxOkasIaF3VZTD9lahsnhTqjCj+6Dfwq+wvIQbJw8k6LX5LzI7Lwlut2wI6N1foapn6d4ZhKAW
rQinqocJeRzLIXTN6p7MvzHu0sM1GIy6lXDl3fIeeSPCtn2lX0R8CmwwvWkOezQKJVxDhThAJ17Kp9D/ghI8qWlqgL6qdR30mxV0
cO72ckJ50hJpz8RY6AhFRTpYBg0JUWx+WDnEEok4hUulsRt4TyJWmHjIN+QdEVFW0OrjsEMOm0XZNmFxK9Zb1gRFekGJ+y4RhtOY
D3lXjxB45b//diLunoQI5lrRLmDR6Daqo0Cq9VA6NiZA+FxwcnIKNoc5n1UYme+DkjW1/pfTrihPOj2S++u/uwoy6nsgxTApxNXW
EnN028qyGdIbT1VpwJcvD0ukTglDkGBrgpqccwbLHtDyXG83Z03aqmdepd0V+N7CQXg/r320a2eYqJhHf/d5RuqaZV7GZo5VHCff
8OZgIgpNIg4cCt9AU9jMTbjLol3h7FlzkVDlFaaY4L6+Yc8VoSXctPhzCp+oj01j2KMTW/o2U2sZYnVplxgpquyj3pf26waWwcNm
YUe7ufmmugih6eyvX506EHtLDy9uzHLx1G9OaKhbqnL3BuENXDYRnVyNRvLxumG8moS0cYczM2aN8wUw/25CH9MJJXss3hs+jzuH
ZgXTsveyyEEMCZ43y75/Q1RNJihqwDp24EfRHqk6ZSbo7+uiDySJwkpDcI4ykCe7ZTKWaYRU9s8sll2KyIgLRzEwzB7yP5IzJk30
xmaf1o55m4mWHP5pAy7xzcv22oih6X/ugwjImEq/5Vqhg2yBAIaslKOgR5oAciGay978/BoPWfWGfpZ/jGaqVdgoH25Fwb6yWF+m
94jc3mWE034EWhN18EmvfQf1XUjeEqQOQRvRIoaApRQBHLMUSLDqhYk40kbVP2G4BsLXkG2EEITZSQdC/arnOqFsVZqTicOkzElI
Y2bbPnsBQ6tC6w9K3bZTIE89WEunQA0U8YjJy7s4KZ5HWvRFliVvgzbbiAZUUx10cqKE6/bj9o/syluqSz7N2za3Esb4lncsU+6T
H3UGFBysX38TxPO6n42g0PgBB50P7xd52hBOxUmJ2yBZOcjBf9iabNXd0L5fsJFh4KxMKzbdFUHeZA0RBPUlCTIOexbM40KSEAiY
PeATJl/BIp+B/GXBYiwKOIp5fSuhyjQtPFqhDUtGsf1DRLOMVfUOfyNlPsH09NocjufzMBjidkMWAAUka5VSXTvL7qhTX9H0pbAA
tVA/mhAHpe5IXbZggxOACDSOUNi9+HQY+hc9h9aZ57FX6kc+OTXlC7Gd3SvS/x4r4ugxQy+IU6wV0A9KOGx8dIDrka60bfejkepQ
4on6OXtGW06Xf6qFUv1ROvqiBPm09A3JZLu2cS9iFWmgyMEpZPS75BijO0ulGXhJHVcU0qj2AlaAqiPVFBrV2GSDQVNS+9TIpJ3J
BHvs81ytY+BUai10Vgq62Z3BRHrPy4/WKxHXiA/Ml5psiT+OSqHAsC8tVgJtC3Rpb7nrrCTKrphV2wVdTtibWjFd9qaUn3mJZgHW
HK7w+slL/wqiqMDXcLtOLlyHcMy6MTcyZAMLRJ4M/UIPjSSyYBV7ZWsM6xNR5SdUpJUxw5TVgMMSuMl4wR7AV2qhVFFDotGBfN+h
xhj02WO/kCMXUG8lLEUqMpfefKTBgW5c7vCJa5CTLC/+3FgByk8RwKDFBI6glAaxcDjTDrUYZZRWXRPA8heUkgg+0emPkmrj/+U3
HIoV3uxX8ZqJbL3lAQPVEKzRgFZGC3x6WCu286SnhMfi6zZHzkGT6r63qah2PCT2Wsvqxy0J66vozrXjtFrevBfTl0YCNEZKQliT
zzL6shV47IL9Hiswn39xI7TsVhjRvzGICa/puttk4s/Z1NOwejFGZ//xQXOwN3toWfTizZt5mBaQp+thhPmyLR4sBkkOSYpw/U/H
bpS8kUKRXAocvX77qbgvU9+JpeVCzPBeb2GqV3RyT0wUJTp7628xxDWRDt5Yx7ykcElMRg/bax1aLcISdJWUtzIqVu9O6tvPNuqp
cz3evBTjb0h0+jXqcQsSPPEFJgJLETtWL67UyLcUPkzHkCGaA7pzX3Grm8GUJM/MSkikFWSpG89Eeg19UXkB0CrmcTKcYM4DOfgt
VnDlDBSiSTcd5iayXwE6q5pE6o60ka80tfVx4YmqxXkwhD2wdm8RTg6P44lVYZ1j3EemBk0f0P4Q6uB0EZkfE4nBu20Ui6zfPTYe
5XQELVBJB3+dWCTxKo7MIkAjEJxlu5gUFjOGqQYrvmfrfxZX5vluBOZ4hj85yPXML1xm3uMpoAp9V3IL4mEk7KEJ5N5YA6Miqm37
vIG1ed0wwx414urD82rZSUj4k714upSblW3pk3b+6FgM43YHwQFlbw/XcTwSRkguFGJKFtGHa34//ARPPHd6kzAmCnMcYGYIwWN/
Eow0g9NsgaIPafzJWWPeDj/PACeSEKHqGwd6vjMFxStuOwgrbnU7mdH51u96zS2fuTQUIdj9Ei2WDGB59CVRtVV/Ig2gehudUTVW
UYEtThWcdhG8iMrtz86gnTYS0qOyj/hWEU5dGy7GBIUyJPEmLvV3bwoN/fERTQrnk0XMg016N46UE9KxILzyac8ph9eI6oA4V2xs
rL1pmF7Emexd6S3EYY1HVk951YitthIcKjb6nCnotiPs4tVhCS36Na+MTP/uHxH8Howrmc1KUAJJpwPuyN2kgGb9fcAFu9W3dHgr
GCERcJ/QuGqhQFKh86l6bIZPU2OrM9N5JiuFK9MgNUY/m6CDQTDnx3SJeYthB6vosQaPut2wKXvn+CQ6php9f4GLqtIwuc12qJgf
1cgSWdcNo+A6e2+FLczQsyayW9xeo/igh70M5AwxEfBsVx+VoaElVNOEY3NJShBFzEifbER+Xsad5cqz95CWIWfoE9onenZoYcow
GehAzSp8snXkWa/01eLDC5DTUYRCi2xWi10gkkZc6jEdSj+76+PKdE2q0x6ZWHK10pvGUYKuFn9yaPo2T/7I0J9Cy8c7lCpFWR5u
TwvtznJFdjPvsZ/S1UkaNPB9s0lnIgBkT369Cd1ix/Nz/4F1TIKoDCCUiJT4ZIHmtLf0Qrum9PSIEVLiKlNOBE+2ZcWOr+FxNq4g
OF9RSjiY9n9vZrUJtkuG0iopYpvP19Oj/TkvDdwNqnA0G8P73dbn1Yia1YEQQ5Q5ApkpqCx3ecvNw1vy+ghn6qaAQeHStG0P5JRD
mje7nlO6rz3nRYKSkALtM3JDT/MmJRo0gC/wAb/GNtyX5i4HWgNSi4RgO78Bow8esVsMGCp+uPQcK0mXMFNuyxtmsiS1rE0k4B1B
8Z4lqNseAxFB6hDwjgzYIp07WN7Ijdx028wPUfLylvzKR7tAGX0k8zg24Q5BG8pYcMkiexhCX/Rsw8U9HuM7bN4QDg5cySQYxM0z
UklylG675LOp31LBJe6y3Q2jZNS1smQVMunmg/OYP1JOOC0ASbGomN+NywNfPUV/+qZc79zFjMaVzWG979AwCgzFm5yuqg4EWGpv
lGyVyzhy3Z/83AJwHLSII2/90sDPHmULyhRWF6ZqIIBPRfM5jx6n0pp/zUxLDKXBLd2xA9BVbU8iPuyNLIsrMhJkoJfyFyguvSO8
SuXevNnP/jwWbA0nSsnp3IMFobV2cRT1ycUUmAEc6hCplQVTBu+fcPpx49AXQS9/kBXZi0Qp4DLr8y8c+kOnrHpBklL0PRonzfUn
w3Ng56EW2EVUVSMtmY8AsksD+gR+htBNDUtjmZvSOX+aYVXiDPkYuAOfhQQRmHFYqhuPpKTZ2l7dZo7qBjUyUU8eBPAXxnXfR7Et
TXdVn9719c9rRdKZQf4E11kBnXfNLOKWhQnlbWKRQfqJdjxjsuzCnkdHBAkO7HqFy+bthtazIAO1wT3d5vmXi+5AqCdy84vhlz/R
jbrPvTKd3i+b7dIl3JmvEezyUelnIjA5bCfLFrHXjE4lYWpq1F2Em+CVeVy27UemokcNI9fyzpv0uNVWbAa/HIHQE6g159Rhb+GN
L6mQoF9Yp1lSstvuujij/iZXtVE2fHkL41/R9au0KfPswZ9EtQ0hu+ftTyOHIJjpqyV88AtcEzG2aBELVXx3gIIaonyW/Ffx7Yng
iFkAdUHqPY2W1/HnYb9Ru3gO+jxqod6RQs7gw8YZAJsx59LTCvLP4DWFGSfGi1VMuMQ48Y4pqk1Ro5kmvBkbD5wEOAUKD4yIX7H+
dXLVIcHWoDSH+oC6x8Iozd00KHx0HZToHb4NFaWOO7KSXIgCrtgrsQi/cR+1A0Lymum8/ToI5WRzt4JOeVTdlUveLr+1SjgCFvCr
Z6I0/U9lGvLXS2BXinJvCagp2dasnZa+rdFW+fPN+LAv7z+TaBGk2WO6HWk1lqvGGkngaIj3HRh2yk6j5Z4XuJUxL0wkpzWlNCn5
iQp5L1u68/mZeqsv8zVP7bABzJtRzKoi/NxSoyCqWb0rUH84ukJnn/NcBYW8iiociHrNZEp0ORDfzMFvNsTy2usQHRjw8K9kxu9U
K2veoWxs+ViPdatxHJ45n1qPLr8Et1Es8N9GeCvfhq7xfM53aIk9C526+31HqgycHXCRpkeT84tlI2ZJf+XGZSQpLfTwpWnioD0w
Yaq8idcatuz7aZXFUfLrLMtxvBqjft5mF+fzpOsHx4pbWPTxCd6QwJ9mymvuNnRjwT5YFOcST/kw5wvchywGmt4WCP8TA0emMUm3
CGeBn+yQ9kW2muBtsTmAqFxPZUCqQh2Evp0d6zCNmMZf2mYPj/5jzpqJhI9Cew7VqPYC2YOX3S1u5uIuW7ERo7w0WehjH4B6op4r
vKDFNmf71q18zHva0l1vyL08oJQ0rZg2b+rzbLtgWH2HzLhXYENSbwYAjysR62sl4irhKsXCdG4dFWVD+kcFZVT/MbIeZrGxg0jD
EykJdSs8Ry7PwZTF7mFQErKGuTcFAtCw0pf2oJSPaZ3oYPG8dMmX3st3Sj1ZSqvpb72fiAjrIQ9+M3pULf97mijuwrXDu5cn95vg
0yBU3lppZowuvKN2TBqV0qO1/YYcEqbB8FQgy8EV2Q226Zyg9ynkctLoXMwdjgggmSpx35fKO1uPvE5QZE6MRfv6EPlCCsxiRs1N
rVrjP+MrSDyXMDM2Um8upWiiuduEJjXr9T2nxFqbdic/qes/gNsBytFkqgtCbIVPxu0wE/qVTkEJ0Ci1GloALilUyeQNQf+ifpdz
GNLfZmLo/yeagpogubJltgKNtmG8x/lk23dEiuxostM50ChatX8qb53jZIyLfPlOjJ1PiNuNvpfvBKmZMC263MpHnI6gwV6HNGgo
WmizRMXbUclWu+4H0Grrp7291XdIQTt8FH93BaH1qoVYRrOKv1G5P7aVGIZHZmuGG4HzgXlDOLuKs4cCg/uiGE4T+aBnjbYUEwsO
mH1mK3qPs5s+PFzHeTY6H1GJ1Om4dUa3Hf1TXnBL5eHjf+fLh7EgAgsvCBCfNNtm/6X+gZG86nJZ9uSYmT564iBRSMFymaWLgRhn
bp87VwOz+3dnpKsC8NmwNyvUz72pOTB2iukIPj5GKRD03KutZLy5MOG1A2xcf6VqlVv5lGYKC2IEob1W5fRTY7yhwtTL5rdpZbcg
VIT7nZ2FAU2lHbyviCim1XVBSq5xeQ8pxRxQso/EzoohIQvRyp1rUkIRyBD4Z/BRr4CLm4qK5ykk9/Xy7WWpjjj7Da78xz9Yp2ED
tp4IEOZBiCkQjvWM5Hu5bow4bgmO1MAsRolT2n+0CS5SPkm+hUQGUT0q2vav5enmlpJ56uE1Ui7n9e/Y+jzfI/V/o+JNcdLFSluG
b+9yO16AwPgjOZHcCiFvySCn7rxy830Y6WR59TVJAZEB4DHAwfaeYruCYI7Aa4jkLT7DzKPCfC965W+fQbsHt0QM0MoMA4wkt03G
+xWVo1EZhMj7sxHYywyeDQ1XLSHljwQW7k7xT3fk+sGOLbe+prla/FQJR8pkg8N5irZ8Lu9FG7EFSJTY6+wVnpJvgZFkrq0a1R7R
moNzeuCgIDPkeE//CeBm7u4u4Wl3qNBaUoBeex5QkxjhUcU8jKthaF5LPJdi+jQbi6uJuO+X3ej6TVstd/khvTikMlA75CvwPEl5
S6wXJE5MiUCtKHnvetFmmBdb6it4rJRm2bDcyyW3OZL+T3w5ETErsCt3NEB4p1BBX7+UcoSMQVFY957/wNMID/Z9wGAlGIrhfK7+
V8wq3gWXcgVUghYgQllMV7UYjzdmmKm9qTZJrN7UC0s+W0Ml0Zb2LfeVQac8Fc4PUboRgi+rE1/Aif+0/LH18N4WTukifeAM6XG/
1h+g2JvlNFgGgdj76izLUdA3orn2a1/fNh3torSQxJTAekHQDtkc2whI/kmo7wYAERaCdmOhJxlXNwCwKV84ygkO1L5UlhQKp/sn
rur/em1nTtd0hU9wcnw2wDHgLduh61LaCxzQGDzIIYmheODjH1cOGQRxe5j6yPyWMKd2rGulK6dopGT/cW4b3rGAqDLrgjovdFrJ
n2/1CGk5MDCbyPv7w0flUTfASsZJVVZsPTCB7aZuTnYgU61o4tn9muXgkdXmScD3Pt5H7Lzat3RMU8CnFNAeOGOpO8CWLGHgXQrp
9q8RWg774N4ko/YReDWQPlTWQjBvY2yOza0FWGk2ctrkCLucjihNV0z7lVzmHprP402Lc4s2Tvyh0ENpkSdgRvaFxzBiDGX5MBP7
Pq2H+ahlTyEi4VyZu4SbnJhHkei2UMGjjA8LKZ8dp1YqYHQf2JWIBpUxMDKZBy7o7jWAaMtOk9X7TvaGmgmcrDElpnlB73fRQ9fC
on+Z360vch+1jLJ7Zk5kct9cRwdC+L+YpNLFRUTad04Z7MceiHDdP5qUaBZM4mJxipAfhWzI9bZPimWvUFcOCwOw8VcnBbZKz7hg
yaz3hYGzw/s7rPdFsPNExOF8gojuQ7uRDpIjvqNm28Gu8hIMqYX+ugYlHq2acJueJsDwy6laeV3Q6C60/pa8xwM3Pi6xYLG86gQK
tL3d86TT4Zb3eGDo8vEVMtuPHlLBbF9J7iQr4sILK8VXxatqslnqDA8b6kXduiDbR9Y0NiidIepQqmGm0luQcOAplVg7mCvT4hoh
xF4+RElFD72BqK9iQNLLSdYU81qxPs8IX/iS2HZmg5h3Q7mKtCtvQcwjkt9WBNkPE7C9is6ZHRb6LsyPdHgn+Y1ANHfaWvIvNmJy
TamzTFaqD92sC00fEboIUDwsmpuFepEYDiLPrebUfok1dla4qjVMKX004i40lTvhUTZunrshRwL32RbELxlt2eqSUqOtqsISMJra
sGLhfLdXC8jhbRDWMwLUsX+dIMoOloHrfBXAaHvqfiTo1eXj0TuZFsMdum3mpQdlZ7UZW/aT+67j3a7ydtf8S5NhRjM/3IZrpL1y
P9u+22lbYRLrWlbE7tZk+QOprX1trFZ5pVwQ2d0G0wLtIyUq0anxctBrOhltABLnifDdCHIeeSxPwR8pgDeuJeMWta0BYJz6chNF
47hTurJDanMWYGDoKKWnz+hLcKoBQv4pvZMbz0L2mQ+UwY5E4dfPR3vxRYDNtVTLqqKb6WtNrbvIJ8s4MgGtM0nkx9moSyolS3Ao
AMNEC8R9zbYj1Cb+I96ls/OnQrTzfZAETS1pLdlnyWewmIbyFH2BF1pyaOd3zxwtHoNwID0vPPdUjB5YInfiTBI27HfmI9J8MMBo
VzZWX2aBQcPyQSdyTuoEP2JLOpwp28n5VMeZ04bmm2Pzd1oiRF+bQSe5Yw4KiVp0z8Pcm/Btvb+jp6ZM55+/GLO4kuPr2dqNJoNA
CoyHg7wrbtZf5DsMWvDnhaLvcidQTQIzbcGJWSiFKUn0GXn33YHEP759Ms8HmjHTfOexoyT3QQVpnhrLnh0euM4ET67NqUdXSFrL
DMGB1wRmkxD2SdyssvoYKp3fRrRHCzQbgSALouLmtDCmhNosW4r83qR6e9PAkZkXIVhJvlDN8DE7hxosDgtozL/ISJWZXH0E+kva
muMxurzZkX/5wVSf+r2KzJF+m06PhI1pjeX8790kEZ96GLLY4PXpDmL+dvYJDHKk5AdyzkTCWQ196I2L9iKpN+oSscun+RQCQdur
VfHbh0if5p4/Bpw/tpPv/oa2CfsXr4GiEd7Wl/IVobc1veIDl1mgfB1E0L7jAc4QRL2ds3mvX6W9YQQp6vnDvxFk59rVoSUIj9Et
vVcXeKKZ0eh4BXXiq1/NNPSN3Ir38+R/MAJZzL1nejY1iA7XCVgVpQ/b2O4tciSB/r1zLUtO2/aHUvsaav3RsNcoahrlejsbkEUJ
EQE1UyK7dVrosQhX8FuEXmU00TDbmT6oujvLsbgLqsS3AF72RCYDrGIbh9uoZziQeVl+nf0vuUekNvwzyb/ZwydnBrp2nw/WmiJK
yx9dMQkOIys4WFSUIYkuNndMcbVkfTKM79+KURuhCA2OCliQi6gPBcSenUJEXpjVEEffYgUZfdY2uEZQ9ZlDDsLVWHYf2Y/LZZnp
WkhY3bw5zCmDFu75fiIMXHiMe62lOvRoDwyjkaTTyzD/Oizrtx1JeJYyGKkUb5aU+X5feR0LjopzWCe2SoTPmQuFjWMKUhhjD5Zt
EmhkhEnsP2YjIs/0eja9eAAbLN7nC1YfOc2hv28erJmxmvSBVBJoLH8PvIjXIDxVcie52iikgm+HtpyWK91VMBf0hhBg+kKYo8t1
idhujC9YdF2A+mBHYS8Z2QPCnLwZrCcl/1eYPOBOGa3aBqHzbjnGSkbbFn6zWGCF0GHxtoZFM8+xC2MYyiqBussRTgjmFOTKdCxi
phSNURIeshGjLVr8XCmV1sj6xFdnkiqHTNuua+m7IoNq42j/JWvEzpzgMTtPvOJ3StFtQoj0pPkeLnu/gR0hY+l7H2u1+GmuLxrJ
YPLOMr6Z+cbBMy5I9FrhORD7b3a17ApDaiPSz4ptVv3dAL+YxdTCojNuzjxvtL4WINVHvWj9obwN2vs2ew4qt17fRrITX11fITZs
vtReaNEixFER9A9uP+XsDz2aDAdrqcMK6Ceq3wk6+yq3i9BRqzeF+GRpBG2ld41vQ9Fx/ESKctNn268vI3eKH+kHlzBXMfJbYXYx
bOHWVIKyf02PPL0KJ1qVzTTS5YVXhKhwEySKrJ/3eqTHrS+hBDmnoir2xtEP46fidxaKAm8uy1krfz1K7dGuhKXKIumneUjbLN2h
cPtNwCWSc3B4hDzzuHL/37onysJy1Cma9Ml7sw9x1HoVgs0p45HngA4ddT/tSRjXkF8eddCsHMD26XkZHoYogWoXYgjL01757pkU
VTnwjECfCWSaa0/5GbttaWDmkDXm4q+zkVfoDIkjlBP4EpScFdb1uo3NFhYiV+0qA5Vo65jrCWDKAKo30/ExFYl0IRWIIGX1wvio
nolP3UaXZO/5SatzxWI+HqsbudeLKMYqn61UovPyJy1Ph2muE7eXDtJLu9zCpD5POUmOWjpg0cBZARc2AFD7+XIayDbyAb9FTpRL
0SwDTc+hFFiZ0HWHLOC0XAcRyFSV6hFA6DsnzGKl1Jci4uTAl+q3AYPnIavJQd+rcDNPfzcp/ErLpbUll+ezhDtSSfpcBbrEEXah
y24fUWuzke+t61t3hauO1jP2/FuKM6B+AstFp6QVrCFZXO0wYyvU/8L12W2jjnD3+EeeZNZaVRNcTcZC3qUMhlXLoRrq73DCbV9M
8bPNUFMxmMGHxaqGxM3Vz/iPg1mi0GuEFu3AYko+9qfSpLu+kdl5cifLi3eg2SYkagiUPHm68Q5x9x+NX6Aqf+IzzdExkZOGlV5l
v8M2exArnq5CeQK0ht0Mazzz6FSkI5vCW24O8FP5jPPgt49zg5xMAuLjw7SFNKcUPZ8WTVgRPRMKeCRpiDwqAREcw6qP1pbO8nf/
/3qwKsI=
```
````````

beautiful, isn't it? This is actually way fewer characters overall but split over more lines. of course, this is 100% backwards compatible with the old way.

@kiki-lee please let me know if this improves your life or if the old way is better.

@jwunderl is there anything i should add to make it easier to mark these lines as non-translatable? i forget how that's specified in crowdin, but i could certainly add a prefix to each line to make it more regexp-able

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]
LGTM once ci is green

I'm having trouble finding it in the ui but it's this https://support.crowdin.com/enterprise/custom-placeholders/#configure-your-custom-placeholders -- the only one I recall us having is the one saying "don't translate variable names" if you hover over the % defined variables e.g. in https://crowdin.com/translate/makecode/2424/en-nl?filter=basic&value=0 . Maybe I need to log in to the makecode account itself instead of my admin one? That seems weird though as other settings are available still

**Comment by jwunderl** [comment]
one possible alternative; would it make sense to take in a url to fetch json in assetjsons, and put the assetsjson content either  under /static or a github repo? You'd run into caching issues so we'd probably have to version them (at least, when updating assetsjson contents increment file name and delete old one a week later or something), and it is another network request, but some level of separation would be nice here to make it so we can scroll through md again hah

**Comment by kiki-lee** [comment]
There are two reasons I've been trying to switch to image extensions:
1) Make it easier to update across all levels when brands need to pull their assets (or I want to change something)
2) People have an easy time finding the gallery and a hard time finding My Assets (who knows why...)

I think linking to a json in Github could potentially solve both, if we had a way of also bringing the linked json into the gallery instead of the My Assets.  Although, I think I'd then have the same issues with both json and extensions, which is that I will no longer be able to reference the imported images in the hints.

**Comment by kiki-lee** [comment]
If your option #1 could be available today and it wouldn't stop us from fixing the rest of the issues more properly (relatively soon) I'm cool with starting there!

**Pull request closed without merging**
