### PR TITLE
Mark property signature statements as readonly as well as declarations.

### PR DESCRIPTION
**Pull request by matthewtebbs**
In some work I'm doing with PXT attributed interfaces I've noticed that readonly property signatures in these are not marked read-only. They should be.

### CODE REVIEW

**Comment by matthewtebbs** [comment]
There's a file dependency issue on clean builds I believe. Not me. :)

```
[built/webapp/src/app.js] cd webapp; node ../node_modules/typescript/bin/tsc
src/fileworkspace.ts(238,20): error TS2304: Cannot find name 'Util'.
```

**Comment by pelikhan** [comment]
Try merging master again.

**Comment by matthewtebbs** [comment]
Done.

**Comment by matthewtebbs** [comment]
@mmoskal

**Pull request merged**
